### ISSUE TITLE
Google safe browsing thing doesn't seem to work

### ISSUE THREAD

**Issue by alazymeme** [pajbot/pajbot#1223]
```
Traceback (most recent call last):
  File "/opt/pajbot/pajbot/modules/linkchecker.py", line 487, in check_url
    self._check_url(url, action)
  File "/opt/pajbot/pajbot/modules/linkchecker.py", line 524, in _check_url
    if self.safe_browsing_api and self.safe_browsing_api.is_url_bad(redirected_url.url):  # harmful url detected
  File "/opt/pajbot/pajbot/apiwrappers/safebrowsing.py", line 11, in is_url_bad
    resp = self.post(
  File "/opt/pajbot/pajbot/apiwrappers/base.py", line 94, in post
    return self.request("POST", endpoint, params, headers, json, **request_options).json()
  File "/opt/pajbot/pajbot/apiwrappers/base.py", line 81, in request
    response.raise_for_status()
  File "/opt/pajbot/venv/lib/python3.8/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://safebrowsing.googleapis.com/v4/threatMatches:find?key=xd
[2021-04-16 08:39:18,647] [ERROR  ] LinkChecker unhandled exception while _check_url
Traceback (most recent call last):
  File "/opt/pajbot/pajbot/modules/linkchecker.py", line 487, in check_url
    self._check_url(url, action)
  File "/opt/pajbot/pajbot/modules/linkchecker.py", line 524, in _check_url
    if self.safe_browsing_api and self.safe_browsing_api.is_url_bad(redirected_url.url):  # harmful url detected
  File "/opt/pajbot/pajbot/apiwrappers/safebrowsing.py", line 11, in is_url_bad
    resp = self.post(
  File "/opt/pajbot/pajbot/apiwrappers/base.py", line 94, in post
    return self.request("POST", endpoint, params, headers, json, **request_options).json()
  File "/opt/pajbot/pajbot/apiwrappers/base.py", line 81, in request
    response.raise_for_status()
  File "/opt/pajbot/venv/lib/python3.8/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://safebrowsing.googleapis.com/v4/threatMatches:find?key=xd
```

**Comment by pajlada** [comment]
Works for me - are you sure your API key isn't invalid?

**Comment by alazymeme** [comment]
> Works for me - are you sure your API key isn't invalid?

Yes it appears to be the reason why, apparently I deleted all my projects ![pajaDent](https://static-cdn.jtvnw.net/emoticons/v1/301512758/1.0)
