### ISSUE TITLE
Linkchecker : Error while timing out blacklisted links found with deep search

### ISSUE THREAD

**Issue by MagicHack** [pajbot/pajbot#1457]
For links with redirects the module finds the bad link, but fails to timeout with the error : `AttributeError: '_thread._local' object has no attribute 'moderation_actions'`

Full trace
```
[DEBUG  ] LinkChecker: BAD URL FOUND https://www.test.com/
[ERROR  ] LinkChecker unhandled exception while _check_url  
 Traceback (most recent call last):
   File "/opt/pajbot/pajbot/modules/linkchecker.py", line 504, in check_url
     self._check_url(url, action)
   File "/opt/pajbot/pajbot/modules/linkchecker.py", line 552, in _check_url
    res = self.basic_check(redirected_url, action)
   File "/opt/pajbot/pajbot/modules/linkchecker.py", line 480, in basic_check
     self.counteract_bad_url(url, action, want_to_blacklist=False)
  File "/opt/pajbot/pajbot/modules/linkchecker.py", line 362, in counteract_bad_url
    action()
   File "/opt/pajbot/pajbot/modules/linkchecker.py", line 331, in action
     self.bot.timeout(
  File "/opt/pajbot/pajbot/bot.py", line 626, in timeout
    self.timeout_login(user.login, duration, reason, once)
   File "/opt/pajbot/pajbot/bot.py", line 629, in timeout_login
    if self.thread_locals.moderation_actions is not None:
AttributeError: '_thread._local' object has no attribute 'moderation_actions'
```

**Comment by ALazyMeme** [comment]
Cannot reproduce, which commit are you on?

**Comment by MagicHack** [comment]
I'm on the latest commit 9ce33a46fdf0b9e7deb711496825317e19e34e5f ,
I blacklisted test.com/ with --deep option and sent the shortened url shorturl.at/bnMPX in chat.

**Comment by Felanbird** [comment]
![image](https://user-images.githubusercontent.com/41973452/133220790-106f7e82-1c00-44ea-aa28-c169eb2666a8.png)
