### ISSUE TITLE
ActionQueue emote errors when starting bot

### ISSUE THREAD

**Issue by ALazyMeme** [pajbot/pajbot#2074]
```bash
[ERROR  ] Logging an uncaught exception (ActionQueue)
Traceback (most recent call last):
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/pajbot/pajbot/managers/emote.py", line 92, in load_all
    self.load_channel_emotes()
  File "/opt/pajbot/pajbot/managers/emote.py", line 78, in load_channel_emotes
    self.channel_emotes = self.api.get_channel_emotes(self.streamer)
  File "/opt/pajbot/pajbot/apiwrappers/ffz.py", line 70, in get_channel_emotes
    return self.cache.cache_fetch_fn(
  File "/opt/pajbot/pajbot/apiwrappers/response_cache.py", line 93, in cache_fetch_fn
    return serializer.deserialize(cache_result)
  File "/opt/pajbot/pajbot/apiwrappers/response_cache.py", line 25, in deserialize
    cache_result = self.safe_deserialize(cache_result)
  File "/opt/pajbot/pajbot/apiwrappers/response_cache.py", line 72, in safe_deserialize
    return [self.cls.from_json(c) for c in cache_result]
  File "/opt/pajbot/pajbot/apiwrappers/response_cache.py", line 72, in <listcomp>
    return [self.cls.from_json(c) for c in cache_result]
  File "/opt/pajbot/pajbot/models/emote.py", line 57, in from_json
    return Emote(**json_data)
TypeError: __init__() missing 2 required positional arguments: 'max_width' and 'max_height'

[ERROR  ] Logging an uncaught exception (ActionQueue)
Traceback (most recent call last):
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/pajbot/pajbot/managers/emote.py", line 92, in load_all
    self.load_channel_emotes()
  File "/opt/pajbot/pajbot/managers/emote.py", line 129, in load_channel_emotes
    self.tier_one_emotes, self.tier_two_emotes, self.tier_three_emotes = self.twitch_helix_api.get_channel_emotes(
  File "/opt/pajbot/pajbot/apiwrappers/twitch/helix.py", line 598, in get_channel_emotes
    return self.cache.cache_fetch_fn(
  File "/opt/pajbot/pajbot/apiwrappers/response_cache.py", line 93, in cache_fetch_fn
    return serializer.deserialize(cache_result)
  File "/opt/pajbot/pajbot/apiwrappers/response_cache.py", line 25, in deserialize
    cache_result = self.safe_deserialize(cache_result)
  File "/opt/pajbot/pajbot/apiwrappers/response_cache.py", line 82, in safe_deserialize
    return tuple([[Emote.from_json(e) for e in s] for s in cache_result])
  File "/opt/pajbot/pajbot/apiwrappers/response_cache.py", line 82, in <listcomp>
    return tuple([[Emote.from_json(e) for e in s] for s in cache_result])
  File "/opt/pajbot/pajbot/apiwrappers/response_cache.py", line 82, in <listcomp>
    return tuple([[Emote.from_json(e) for e in s] for s in cache_result])
  File "/opt/pajbot/pajbot/models/emote.py", line 57, in from_json
    return Emote(**json_data)
TypeError: __init__() missing 2 required positional arguments: 'max_width' and 'max_height'

[ERROR  ] Logging an uncaught exception (ActionQueue)
Traceback (most recent call last):
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/pajbot/pajbot/managers/emote.py", line 92, in load_all
    self.load_channel_emotes()
  File "/opt/pajbot/pajbot/managers/emote.py", line 78, in load_channel_emotes
    self.channel_emotes = self.api.get_channel_emotes(self.streamer)
  File "/opt/pajbot/pajbot/apiwrappers/seventv.py", line 110, in get_channel_emotes
    return self.cache.cache_fetch_fn(
  File "/opt/pajbot/pajbot/apiwrappers/response_cache.py", line 93, in cache_fetch_fn
    return serializer.deserialize(cache_result)
  File "/opt/pajbot/pajbot/apiwrappers/response_cache.py", line 25, in deserialize
    cache_result = self.safe_deserialize(cache_result)
  File "/opt/pajbot/pajbot/apiwrappers/response_cache.py", line 72, in safe_deserialize
    return [self.cls.from_json(c) for c in cache_result]
  File "/opt/pajbot/pajbot/apiwrappers/response_cache.py", line 72, in <listcomp>
    return [self.cls.from_json(c) for c in cache_result]
  File "/opt/pajbot/pajbot/models/emote.py", line 57, in from_json
    return Emote(**json_data)
TypeError: __init__() missing 2 required positional arguments: 'max_width' and 'max_height'
```

**Comment by pajlada** [comment]
Somehow the redis migration didn't run.

To solve this, turn off the bot, run `redis-cli` and run `SET streamer_login_name:schema-version 2`, then turn the bot on again
