### ISSUE TITLE
Modules with the "Disable warning timeouts" setting don't seem to be working correctly if that setting is not enabled (warnings enabled).

### ISSUE THREAD

**Issue by Foretack** [pajbot/pajbot#2087]
![image](https://user-images.githubusercontent.com/69414142/185743865-49e22f3b-3376-4c6b-921d-688f2907abb4.png)

It seems as if the modules with this setting do not apply a timeout due to an error when the setting is not checked. I've tested the ASCII Protection, Emote Limit & Wide Emote Limit modules and they all share this issue.

Console output of Wide Emote Limit module when that setting is not checked (from ALazyMeme)

```
Aug 20 21:06:10 hendrix pajbot@alazymeme[299419]: Traceback (most recent call last):
Aug 20 21:06:10 hendrix pajbot@alazymeme[299419]:   File "/opt/pajbot/pajbot/managers/handler.py", line 120, in trigger
Aug 20 21:06:10 hendrix pajbot@alazymeme[299419]:     res = handler(*args, **kwargs)
Aug 20 21:06:10 hendrix pajbot@alazymeme[299419]:   File "/opt/pajbot/pajbot/modules/wide_emote_limit.py", line 110, in on_message
Aug 20 21:06:10 hendrix pajbot@alazymeme[299419]:     self.bot.delete_or_timeout(
Aug 20 21:06:10 hendrix pajbot@alazymeme[299419]:   File "/opt/pajbot/pajbot/bot.py", line 726, in delete_or_timeout
Aug 20 21:06:10 hendrix pajbot@alazymeme[299419]:     self.timeout_warn(user, duration, reason, once)
Aug 20 21:06:10 hendrix pajbot@alazymeme[299419]:   File "/opt/pajbot/pajbot/bot.py", line 696, in timeout_warn
Aug 20 21:06:10 hendrix pajbot@alazymeme[299419]:     duration, punishment = user.timeout(
Aug 20 21:06:10 hendrix pajbot@alazymeme[299419]:   File "/opt/pajbot/pajbot/models/user.py", line 282, in timeout
Aug 20 21:06:10 hendrix pajbot@alazymeme[299419]:     warning_keys = self.get_warning_keys(total_chances)
Aug 20 21:06:10 hendrix pajbot@alazymeme[299419]: TypeError: get_warning_keys() missing 1 required positional argument: 'prefix'
```

**Comment by pajlada** [comment]
Does not happen on the main branch, something with your local deployment must be wrong
Line 282 in your user.py does not match the master branch

In your traceback:
```python
warning_keys = self.get_warning_keys(total_chances)
```

In the main branch:
```python
warning_keys = self.get_warning_keys(total_chances, warning_module.settings["redis_prefix"])
```
