### ISSUE TITLE
Bot not tracking uptime

### ISSUE THREAD

**Issue by Mr-Cheeezz** [pajbot/pajbot#2238]
the bot keeps saying the streamer is offline when the streamer is online

**Comment by Mr-Cheeezz** [comment]
these are the logs
```
Nov 22 20:47:48 vmi1065408 pajbot@tibb12[2408]:     games = self.get_games_by_id([game_id])
Nov 22 20:47:48 vmi1065408 pajbot@tibb12[2408]:   File "/opt/pajbot/pajbot/apiwrappers/twitch/helix.py", line 504, in get_games_by_id
Nov 22 20:47:48 vmi1065408 pajbot@tibb12[2408]:     return self.cache.cache_bulk_fetch_fn(
Nov 22 20:47:48 vmi1065408 pajbot@tibb12[2408]:   File "/opt/pajbot/pajbot/apiwrappers/response_cache.py", line 143, in cache_bulk_fetch_fn
Nov 22 20:47:48 vmi1065408 pajbot@tibb12[2408]:     fetch_results = fetch_fn(to_fetch_values)
Nov 22 20:47:48 vmi1065408 pajbot@tibb12[2408]:   File "/opt/pajbot/pajbot/apiwrappers/twitch/helix.py", line 507, in <lambda>
Nov 22 20:47:48 vmi1065408 pajbot@tibb12[2408]:     fetch_fn=lambda game_ids: self._fetch_games("id", game_ids),
Nov 22 20:47:48 vmi1065408 pajbot@tibb12[2408]:   File "/opt/pajbot/pajbot/apiwrappers/twitch/helix.py", line 498, in _fetch_games
Nov 22 20:47:48 vmi1065408 pajbot@tibb12[2408]:     value: TwitchGame = TwitchGame(**response_map.get(lookup_key, None))
Nov 22 20:47:48 vmi1065408 pajbot@tibb12[2408]: TypeError: __init__() got an unexpected keyword argument 'igdb_id'
Nov 22 20:48:08 vmi1065408 pajbot@tibb12[2408]: [2022-11-22 20:48:08,637] [DEBUG  ] Cache Miss: api:twitch:helix:channel-information:197407231
Nov 22 20:48:08 vmi1065408 pajbot@tibb12[2408]: [2022-11-22 20:48:08,922] [ERROR  ] Logging an uncaught exception (main thread)
Nov 22 20:48:08 vmi1065408 pajbot@tibb12[2408]: Traceback (most recent call last):
Nov 22 20:48:08 vmi1065408 pajbot@tibb12[2408]:   File "/opt/pajbot/pajbot/eventloop.py", line 25, in run
Nov 22 20:48:08 vmi1065408 pajbot@tibb12[2408]:     command.target()
Nov 22 20:48:08 vmi1065408 pajbot@tibb12[2408]:   File "/opt/pajbot/pajbot/bot.py", line 627, in <lambda>
Nov 22 20:48:08 vmi1065408 pajbot@tibb12[2408]:     self.reactor.scheduler.execute_after(delay, lambda: function(*args, **kwargs))
Nov 22 20:48:08 vmi1065408 pajbot@tibb12[2408]:   File "/opt/pajbot/pajbot/models/stream.py", line 306, in refresh_stream_status_stage2
Nov 22 20:48:08 vmi1065408 pajbot@tibb12[2408]:     game_info: Optional[TwitchGame] = self.bot.twitch_helix_api.get_game_by_game_id(status.game_id)
Nov 22 20:48:08 vmi1065408 pajbot@tibb12[2408]:   File "/opt/pajbot/pajbot/apiwrappers/twitch/helix.py", line 522, in get_game_by_game_id
Nov 22 20:48:08 vmi1065408 pajbot@tibb12[2408]:     games = self.get_games_by_id([game_id])
Nov 22 20:48:08 vmi1065408 pajbot@tibb12[2408]:   File "/opt/pajbot/pajbot/apiwrappers/twitch/helix.py", line 504, in get_games_by_id
Nov 22 20:48:08 vmi1065408 pajbot@tibb12[2408]:     return self.cache.cache_bulk_fetch_fn(
Nov 22 20:48:08 vmi1065408 pajbot@tibb12[2408]:   File "/opt/pajbot/pajbot/apiwrappers/response_cache.py", line 143, in cache_bulk_fetch_fn
Nov 22 20:48:08 vmi1065408 pajbot@tibb12[2408]:     fetch_results = fetch_fn(to_fetch_values)
Nov 22 20:48:08 vmi1065408 pajbot@tibb12[2408]:   File "/opt/pajbot/pajbot/apiwrappers/twitch/helix.py", line 507, in <lambda>
Nov 22 20:48:08 vmi1065408 pajbot@tibb12[2408]:     fetch_fn=lambda game_ids: self._fetch_games("id", game_ids),
Nov 22 20:48:08 vmi1065408 pajbot@tibb12[2408]:   File "/opt/pajbot/pajbot/apiwrappers/twitch/helix.py", line 498, in _fetch_games
Nov 22 20:48:08 vmi1065408 pajbot@tibb12[2408]:     value: TwitchGame = TwitchGame(**response_map.get(lookup_key, None))
Nov 22 20:48:08 vmi1065408 pajbot@tibb12[2408]: TypeError: __init__() got an unexpected keyword argument 'igdb_id'
````

**Comment by RAnders00** [comment]
This looks like a genuine bug. Thanks for supplying the log output, that‘s very helpful!

**Comment by Felanbird** [comment]
Seems to be happening to pajlada's bots as well
![image](https://user-images.githubusercontent.com/41973452/203673490-2fccde59-c58c-46cc-83ea-93eca71d0ee8.png)
![image](https://user-images.githubusercontent.com/41973452/203673444-0b35c357-4148-4652-9a6e-a351a200e16e.png)

**Comment by Mr-Cheeezz** [comment]
yea i saw it on forsen.tv as well
