### ISSUE TITLE
Timeout command not working

### ISSUE THREAD

**Issue by Mr-Cheeezz** [pajbot/pajbot#2355]
![image](https://user-images.githubusercontent.com/68625998/221311137-774b5dde-ad0c-4761-947d-5187bb392b46.png)
when I try to timeout a user with points it does not time them out

**Comment by ALazyMeme** [comment]
> ![image](https://user-images.githubusercontent.com/68625998/221311137-774b5dde-ad0c-4761-947d-5187bb392b46.png) when I try to timeout a user with points it does not time them out

What version of pajbot are you on? Can you please send some logs?

**Comment by Mr-Cheeezz** [comment]
I am on your dark theme fork which is `1.62`
logs:
```
Feb 25 04:13:11 vmi1065408 pajbot@tibb12[61324]: [2023-02-25 04:13:11,494] [INFO   ] Successfully updated 31 chatters
Feb 25 04:13:11 vmi1065408 pajbot@tibb12[61324]: [2023-02-25 04:13:11,494] [DEBUG  ] ChattersRefreshModule::_update_chatters function took>
Feb 25 04:13:15 vmi1065408 pajbot@tibb12[61324]: [2023-02-25 04:13:15,747] [ERROR  ] Unhandled exception from tweepy.get_user (v1)
Feb 25 04:13:15 vmi1065408 pajbot@tibb12[61324]: Traceback (most recent call last):
Feb 25 04:13:15 vmi1065408 pajbot@tibb12[61324]:   File "/opt/pajbot/pajbot/managers/twitter.py", line 280, in _run_twitter_stream
Feb 25 04:13:15 vmi1065408 pajbot@tibb12[61324]:     twitter_user: tweepy.User = self.twitter_client.get_user(screen_name=user.username)
Feb 25 04:13:15 vmi1065408 pajbot@tibb12[61324]:   File "/opt/pajbot/venv/lib/python3.9/site-packages/tweepy/api.py", line 46, in wrapper
Feb 25 04:13:15 vmi1065408 pajbot@tibb12[61324]:     return method(*args, **kwargs)
Feb 25 04:13:15 vmi1065408 pajbot@tibb12[61324]:   File "/opt/pajbot/venv/lib/python3.9/site-packages/tweepy/api.py", line 2508, in get_us>
Feb 25 04:13:15 vmi1065408 pajbot@tibb12[61324]:     return self.request(
Feb 25 04:13:15 vmi1065408 pajbot@tibb12[61324]:   File "/opt/pajbot/venv/lib/python3.9/site-packages/tweepy/api.py", line 265, in request
Feb 25 04:13:15 vmi1065408 pajbot@tibb12[61324]:     raise Forbidden(resp)
Feb 25 04:13:15 vmi1065408 pajbot@tibb12[61324]: tweepy.errors.Forbidden: 403 Forbidden
Feb 25 04:13:15 vmi1065408 pajbot@tibb12[61324]: 453 - You currently have Essential access which includes access to Twitter API v2 endpoin>
Feb 25 04:13:20 vmi1065408 pajbot@tibb12[61324]: [2023-02-25 04:13:20,848] [ERROR  ] Unhandled exception from tweepy.get_user (v1)
Feb 25 04:13:20 vmi1065408 pajbot@tibb12[61324]: Traceback (most recent call last):
Feb 25 04:13:20 vmi1065408 pajbot@tibb12[61324]:   File "/opt/pajbot/pajbot/managers/twitter.py", line 280, in _run_twitter_stream
Feb 25 04:13:20 vmi1065408 pajbot@tibb12[61324]:     twitter_user: tweepy.User = self.twitter_client.get_user(screen_name=user.username)
Feb 25 04:13:20 vmi1065408 pajbot@tibb12[61324]:   File "/opt/pajbot/venv/lib/python3.9/site-packages/tweepy/api.py", line 46, in wrapper
Feb 25 04:13:20 vmi1065408 pajbot@tibb12[61324]:     return method(*args, **kwargs)
Feb 25 04:13:20 vmi1065408 pajbot@tibb12[61324]:   File "/opt/pajbot/venv/lib/python3.9/site-packages/tweepy/api.py", line 2508, in get_us>
Feb 25 04:13:20 vmi1065408 pajbot@tibb12[61324]:     return self.request(
Feb 25 04:13:20 vmi1065408 pajbot@tibb12[61324]:   File "/opt/pajbot/venv/lib/python3.9/site-packages/tweepy/api.py", line 265, in request
Feb 25 04:13:20 vmi1065408 pajbot@tibb12[61324]:     raise Forbidden(resp)
Feb 25 04:13:20 vmi1065408 pajbot@tibb12[61324]: tweepy.errors.Forbidden: 403 Forbidden
Feb 25 04:13:20 vmi1065408 pajbot@tibb12[61324]: 453 - You currently have Essential access which includes access to Twitter API v2 endpoin>
Feb 25 04:13:45 vmi1065408 pajbot@tibb12[61324]: [2023-02-25 04:13:45,434] [DEBUG  ] Cache Miss: api:twitch:helix:stream:by-id:197407231
Feb 25 04:14:25 vmi1065408 pajbot@tibb12[61324]: [2023-02-25 04:14:25,419] [DEBUG  ] Cache Miss: api:twitch:helix:stream:by-id:197407231
 ESCOC
,494] [INFO   ] Successfully updated 31 chatters
,494] [DEBUG  ] ChattersRefreshModule::_update_chatters function took 5524.095 ms
,747] [ERROR  ] Unhandled exception from tweepy.get_user (v1)
nt call last):
pajbot/managers/twitter.py", line 280, in _run_twitter_stream
eepy.User = self.twitter_client.get_user(screen_name=user.username)
venv/lib/python3.9/site-packages/tweepy/api.py", line 46, in wrapper
rgs, **kwargs)
venv/lib/python3.9/site-packages/tweepy/api.py", line 2508, in get_user
est(
venv/lib/python3.9/site-packages/tweepy/api.py", line 265, in request
resp)
den: 403 Forbidden
have Essential access which includes access to Twitter API v2 endpoints only. If you need access to this endpoint, you’ll need to apply fo>
,848] [ERROR  ] Unhandled exception from tweepy.get_user (v1)
nt call last):
pajbot/managers/twitter.py", line 280, in _run_twitter_stream
eepy.User = self.twitter_client.get_user(screen_name=user.username)
venv/lib/python3.9/site-packages/tweepy/api.py", line 46, in wrapper
rgs, **kwargs)
venv/lib/python3.9/site-packages/tweepy/api.py", line 2508, in get_user
est(
venv/lib/python3.9/site-packages/tweepy/api.py", line 265, in request
resp)
den: 403 Forbidden
have Essential access which includes access to Twitter API v2 endpoints only. If you need access to this endpoint, you’ll need to apply fo>
,434] [DEBUG  ] Cache Miss: api:twitch:helix:stream:by-id:197407231
,419] [DEBUG  ] Cache Miss: api:twitch:helix:stream:by-id:197407231
 ESCOD
Feb 25 04:13:11 vmi1065408 pajbot@tibb12[61324]: [2023-02-25 04:13:11,494] [INFO   ] Successfully updated 31 chatters
Feb 25 04:13:11 vmi1065408 pajbot@tibb12[61324]: [2023-02-25 04:13:11,494] [DEBUG  ] ChattersRefreshModule::_update_chatters function took>
Feb 25 04:13:15 vmi1065408 pajbot@tibb12[61324]: [2023-02-25 04:13:15,747] [ERROR  ] Unhandled exception from tweepy.get_user (v1)
Feb 25 04:13:15 vmi1065408 pajbot@tibb12[61324]: Traceback (most recent call last):
Feb 25 04:13:15 vmi1065408 pajbot@tibb12[61324]:   File "/opt/pajbot/pajbot/managers/twitter.py", line 280, in _run_twitter_stream
Feb 25 04:13:15 vmi1065408 pajbot@tibb12[61324]:     twitter_user: tweepy.User = self.twitter_client.get_user(screen_name=user.username)
Feb 25 04:13:15 vmi1065408 pajbot@tibb12[61324]:   File "/opt/pajbot/venv/lib/python3.9/site-packages/tweepy/api.py", line 46, in wrapper
Feb 25 04:13:15 vmi1065408 pajbot@tibb12[61324]:     return method(*args, **kwargs)
Feb 25 04:13:15 vmi1065408 pajbot@tibb12[61324]:   File "/opt/pajbot/venv/lib/python3.9/site-packages/tweepy/api.py", line 2508, in get_us>
Feb 25 04:13:15 vmi1065408 pajbot@tibb12[61324]:     return self.request(
Feb 25 04:13:15 vmi1065408 pajbot@tibb12[61324]:   File "/opt/pajbot/venv/lib/python3.9/site-packages/tweepy/api.py", line 265, in request
Feb 25 04:13:15 vmi1065408 pajbot@tibb12[61324]:     raise Forbidden(resp)
Feb 25 04:13:15 vmi1065408 pajbot@tibb12[61324]: tweepy.errors.Forbidden: 403 Forbidden
Feb 25 04:13:15 vmi1065408 pajbot@tibb12[61324]: 453 - You currently have Essential access which includes access to Twitter API v2 endpoin>
Feb 25 04:13:20 vmi1065408 pajbot@tibb12[61324]: [2023-02-25 04:13:20,848] [ERROR  ] Unhandled exception from tweepy.get_user (v1)
Feb 25 04:13:20 vmi1065408 pajbot@tibb12[61324]: Traceback (most recent call last):
Feb 25 04:13:20 vmi1065408 pajbot@tibb12[61324]:   File "/opt/pajbot/pajbot/managers/twitter.py", line 280, in _run_twitter_stream
Feb 25 04:13:20 vmi1065408 pajbot@tibb12[61324]:     twitter_user: tweepy.User = self.twitter_client.get_user(screen_name=user.username)
Feb 25 04:13:20 vmi1065408 pajbot@tibb12[61324]:   File "/opt/pajbot/venv/lib/python3.9/site-packages/tweepy/api.py", line 46, in wrapper
Feb 25 04:13:20 vmi1065408 pajbot@tibb12[61324]:     return method(*args, **kwargs)
Feb 25 04:13:20 vmi1065408 pajbot@tibb12[61324]:   File "/opt/pajbot/venv/lib/python3.9/site-packages/tweepy/api.py", line 2508, in get_us>
Feb 25 04:13:20 vmi1065408 pajbot@tibb12[61324]:     return self.request(
Feb 25 04:13:20 vmi1065408 pajbot@tibb12[61324]:   File "/opt/pajbot/venv/lib/python3.9/site-packages/tweepy/api.py", line 265, in request
Feb 25 04:13:20 vmi1065408 pajbot@tibb12[61324]:     raise Forbidden(resp)
Feb 25 04:13:20 vmi1065408 pajbot@tibb12[61324]: tweepy.errors.Forbidden: 403 Forbidden
Feb 25 04:13:20 vmi1065408 pajbot@tibb12[61324]: 453 - You currently have Essential access which includes access to Twitter API v2 endpoin>
Feb 25 04:13:45 vmi1065408 pajbot@tibb12[61324]: [2023-02-25 04:13:45,434] [DEBUG  ] Cache Miss: api:twitch:helix:stream:by-id:197407231
Feb 25 04:14:25 vmi1065408 pajbot@tibb12[61324]: [2023-02-25 04:14:25,419] [DEBUG  ] Cache Miss: api:twitch:helix:stream:by-id:197407231
```

**Comment by ALazyMeme** [comment]
And I assume the streamer and bot have both been re-authed to account for the new IRC to Helix migration?

**Comment by Mr-Cheeezz** [comment]
I had him do that and the bot still does not timeout

**Comment by ALazyMeme** [comment]
Not quite sure what to say. I have other bots running on the latest dark mode update and timeouts work just fine. Are you 100% sure the streamer re-authed the bot as well? Then the bot was restarted after being re-authed?

**Comment by Mr-Cheeezz** [comment]
I just restarted the bot and I got this in logs
```
Feb 25 23:29:22 vmi1065408 pajbot@tibb12[78493]:     return method(*args, **kwargs)
Feb 25 23:29:22 vmi1065408 pajbot@tibb12[78493]:   File "/opt/pajbot/venv/lib/python3.9/site-packages/tweepy/api.py", line 2508, in get_user
Feb 25 23:29:22 vmi1065408 pajbot@tibb12[78493]:     return self.request(
Feb 25 23:29:22 vmi1065408 pajbot@tibb12[78493]:   File "/opt/pajbot/venv/lib/python3.9/site-packages/tweepy/api.py", line 265, in request
Feb 25 23:29:22 vmi1065408 pajbot@tibb12[78493]:     raise Forbidden(resp)
Feb 25 23:29:22 vmi1065408 pajbot@tibb12[78493]: tweepy.errors.Forbidden: 403 Forbidden
Feb 25 23:29:22 vmi1065408 pajbot@tibb12[78493]: 453 - You currently have Essential access which includes access to Twitter API v2 endpoints only. If you need access to this endpoint, you’ll need to apply for Elevated access via the Developer Portal. You can learn more here: https://develope>
Feb 25 23:29:22 vmi1065408 pajbot@tibb12[78493]: [2023-02-25 23:29:22,234] [ERROR  ] Unhandled exception from tweepy.get_user (v1)
Feb 25 23:29:22 vmi1065408 pajbot@tibb12[78493]: Traceback (most recent call last):
Feb 25 23:29:22 vmi1065408 pajbot@tibb12[78493]:   File "/opt/pajbot/pajbot/managers/twitter.py", line 280, in _run_twitter_stream
Feb 25 23:29:22 vmi1065408 pajbot@tibb12[78493]:     twitter_user: tweepy.User = self.twitter_client.get_user(screen_name=user.username)
Feb 25 23:29:22 vmi1065408 pajbot@tibb12[78493]:   File "/opt/pajbot/venv/lib/python3.9/site-packages/tweepy/api.py", line 46, in wrapper
Feb 25 23:29:22 vmi1065408 pajbot@tibb12[78493]:     return method(*args, **kwargs)
Feb 25 23:29:22 vmi1065408 pajbot@tibb12[78493]:   File "/opt/pajbot/venv/lib/python3.9/site-packages/tweepy/api.py", line 2508, in get_user
Feb 25 23:29:22 vmi1065408 pajbot@tibb12[78493]:     return self.request(
Feb 25 23:29:22 vmi1065408 pajbot@tibb12[78493]:   File "/opt/pajbot/venv/lib/python3.9/site-packages/tweepy/api.py", line 265, in request
Feb 25 23:29:22 vmi1065408 pajbot@tibb12[78493]:     raise Forbidden(resp)
Feb 25 23:29:22 vmi1065408 pajbot@tibb12[78493]: tweepy.errors.Forbidden: 403 Forbidden
Feb 25 23:29:22 vmi1065408 pajbot@tibb12[78493]: 453 - You currently have Essential access which includes access to Twitter API v2 endpoints only. If you need access to this endpoint, you’ll need to apply for Elevated access via the Developer Portal. You can learn more here: https://develope>
Feb 25 23:29:22 vmi1065408 pajbot@tibb12[78493]: [2023-02-25 23:29:22,330] [INFO   ] Try to load submodule with ID quest-winduels
Feb 25 23:29:22 vmi1065408 pajbot@tibb12[78493]: [2023-02-25 23:29:22,332] [INFO   ] Resumed quest Win 3 duels and make profit in every duel.
Feb 25 23:29:22 vmi1065408 pajbot@tibb12[78493]: [2023-02-25 23:29:22,333] [DEBUG  ] Cache Miss: api:twitch:helix:user:by-id:505216805
Feb 25 23:29:22 vmi1065408 pajbot@tibb12[78493]: [2023-02-25 23:29:22,413] [INFO   ] Granting admin privileges to mr_cheeezz (505216805)
Feb 25 23:29:22 vmi1065408 pajbot@tibb12[78493]: [2023-02-25 23:29:22,750] [DEBUG  ] Successfully loaded OAuth token from storage
Feb 25 23:29:23 vmi1065408 pajbot@tibb12[78493]: [2023-02-25 23:29:23,342] [INFO   ] WebSocket connection open
Feb 25 23:29:23 vmi1065408 pajbot@tibb12[78493]: [2023-02-25 23:29:23,928] [DEBUG  ] Cache Miss: api:twitch:helix:channel-information:197407231
Feb 25 23:29:23 vmi1065408 pajbot@tibb12[78493]: [2023-02-25 23:29:23,939] [INFO   ] Successfully connected and authenticated with IRC
Feb 25 23:29:41 vmi1065408 pajbot@tibb12[78493]: [2023-02-25 23:29:41,759] [DEBUG  ] Cache Miss: api:twitch:helix:stream:by-id:197407231
```

**Comment by Mr-Cheeezz** [comment]
I just restarted the website and the bot the bot is not restating and I am getting a `502 Bad Gateway`. 
![image](https://user-images.githubusercontent.com/68625998/221382969-3ca7973a-faba-4900-9ab7-ad0610d54c6f.png)

**Comment by ALazyMeme** [comment]
There's usually more information than just that in the logs. Usually can be retrieved by using `sudo journalctl -efu pajbot@streamer`.

**Comment by Mr-Cheeezz** [comment]
pajbot:
```
Feb 26 03:49:13 vmi1065408 systemd[1]: Stopped pajbot for tibb12.
Feb 26 03:49:13 vmi1065408 systemd[1]: pajbot@tibb12.service: Consumed 1.613s CPU time.
Feb 26 03:49:13 vmi1065408 systemd[1]: Started pajbot for tibb12.
Feb 26 03:49:14 vmi1065408 pajbot@tibb12[134959]: [2023-02-26 03:49:14,007] [DEBUG  ] Loaded config
Feb 26 03:49:14 vmi1065408 pajbot@tibb12[134959]: [2023-02-26 03:49:14,017] [INFO   ] PostgreSQL Server notice: NOTICE:  relation "schema_version" already exists, skipping
Feb 26 03:49:14 vmi1065408 pajbot@tibb12[134959]: [2023-02-26 03:49:14,017] [DEBUG  ] migrate db: current revision ID is 17
Feb 26 03:49:14 vmi1065408 pajbot@tibb12[134959]: [2023-02-26 03:49:14,017] [DEBUG  ] migrate db: 0 revisions to run
Feb 26 03:49:14 vmi1065408 pajbot@tibb12[134959]: [2023-02-26 03:49:14,019] [DEBUG  ] migrate redis: current revision ID is 3
Feb 26 03:49:14 vmi1065408 pajbot@tibb12[134959]: [2023-02-26 03:49:14,019] [DEBUG  ] migrate redis: 0 revisions to run
Feb 26 03:49:14 vmi1065408 pajbot@tibb12[134959]: [2023-02-26 03:49:14,082] [INFO   ] Set current stream chunk here to <pajbot.models.stream.StreamChunk object at 0x7f8fe1cb2220>
Feb 26 03:49:14 vmi1065408 pajbot@tibb12[134959]: [2023-02-26 03:49:14,100] [INFO   ] Loaded 1 timers (1 online/0 offline)
Feb 26 03:49:14 vmi1065408 pajbot@tibb12[134959]: [2023-02-26 03:49:14,251] [ERROR  ] Logging an uncaught exception
Feb 26 03:49:14 vmi1065408 pajbot@tibb12[134959]: Traceback (most recent call last):
Feb 26 03:49:14 vmi1065408 pajbot@tibb12[134959]:   File "/opt/pajbot/main.py", line 74, in <module>
Feb 26 03:49:14 vmi1065408 pajbot@tibb12[134959]:     run(args)
Feb 26 03:49:14 vmi1065408 pajbot@tibb12[134959]:   File "/opt/pajbot/main.py", line 40, in run
Feb 26 03:49:14 vmi1065408 pajbot@tibb12[134959]:     pajbot = Bot(config, args)
Feb 26 03:49:14 vmi1065408 pajbot@tibb12[134959]:   File "/opt/pajbot/pajbot/bot.py", line 252, in __init__
Feb 26 03:49:14 vmi1065408 pajbot@tibb12[134959]:     self.module_manager.load()
Feb 26 03:49:14 vmi1065408 pajbot@tibb12[134959]:   File "/opt/pajbot/pajbot/models/module.py", line 102, in load
Feb 26 03:49:14 vmi1065408 pajbot@tibb12[134959]:     from pajbot.modules import available_modules
Feb 26 03:49:14 vmi1065408 pajbot@tibb12[134959]:   File "/opt/pajbot/pajbot/modules/__init__.py", line 35, in <module>
Feb 26 03:49:14 vmi1065408 pajbot@tibb12[134959]:     from pajbot.modules.default_chat_states import DefaultChatStatesModule
Feb 26 03:49:14 vmi1065408 pajbot@tibb12[134959]:   File "/opt/pajbot/pajbot/modules/default_chat_states.py", line 11, in <module>
Feb 26 03:49:14 vmi1065408 pajbot@tibb12[134959]:     import pytimeparse
Feb 26 03:49:14 vmi1065408 pajbot@tibb12[134959]: ModuleNotFoundError: No module named 'pytimeparse'
Feb 26 03:49:14 vmi1065408 systemd[1]: pajbot@tibb12.service: Main process exited, code=exited, status=1/FAILURE
Feb 26 03:49:14 vmi1065408 systemd[1]: pajbot@tibb12.service: Failed with result 'exit-code'.
Feb 26 03:49:14 vmi1065408 systemd[1]: pajbot@tibb12.service: Consumed 1.255s CPU time.
```
pajbot-web:
```
Feb 26 03:49:53 vmi1065408 systemd[1]: pajbot-web@tibb12.service: Scheduled restart job, restart counter is at 3986.
Feb 26 03:49:53 vmi1065408 systemd[1]: Stopped pajbot-web for tibb12.
Feb 26 03:49:53 vmi1065408 systemd[1]: pajbot-web@tibb12.service: Consumed 1.315s CPU time.
Feb 26 03:49:53 vmi1065408 systemd[1]: Started pajbot-web for tibb12.
Feb 26 03:49:53 vmi1065408 pajbot-web@tibb12[135124]: [uWSGI] getting INI configuration from uwsgi_shared.ini
Feb 26 03:49:53 vmi1065408 pajbot-web@tibb12[135124]: *** Starting uWSGI 2.0.21 (64bit) on [Sun Feb 26 03:49:53 2023] ***
Feb 26 03:49:53 vmi1065408 pajbot-web@tibb12[135124]: compiled with version: 10.2.1 20210110 on 01 December 2022 05:09:55
Feb 26 03:49:53 vmi1065408 pajbot-web@tibb12[135124]: os: Linux-5.10.0-21-cloud-amd64 #1 SMP Debian 5.10.162-1 (2023-01-21)
Feb 26 03:49:53 vmi1065408 pajbot-web@tibb12[135124]: nodename: vmi1065408
Feb 26 03:49:53 vmi1065408 pajbot-web@tibb12[135124]: machine: x86_64
Feb 26 03:49:53 vmi1065408 pajbot-web@tibb12[135124]: clock source: unix
Feb 26 03:49:53 vmi1065408 pajbot-web@tibb12[135124]: detected number of CPU cores: 8
Feb 26 03:49:53 vmi1065408 pajbot-web@tibb12[135124]: current working directory: /opt/pajbot
Feb 26 03:49:53 vmi1065408 pajbot-web@tibb12[135124]: detected binary path: /opt/pajbot/venv/bin/uwsgi
Feb 26 03:49:53 vmi1065408 pajbot-web@tibb12[135124]: !!! no internal routing support, rebuild with pcre support !!!
Feb 26 03:49:53 vmi1065408 pajbot-web@tibb12[135124]: your processes number limit is 120311
Feb 26 03:49:53 vmi1065408 pajbot-web@tibb12[135124]: your memory page size is 4096 bytes
Feb 26 03:49:53 vmi1065408 pajbot-web@tibb12[135124]: detected max file descriptor number: 1024
Feb 26 03:49:53 vmi1065408 pajbot-web@tibb12[135124]: lock engine: pthread robust mutexes
Feb 26 03:49:53 vmi1065408 pajbot-web@tibb12[135124]: thunder lock: disabled (you can enable it with --thunder-lock)
Feb 26 03:49:53 vmi1065408 pajbot-web@tibb12[135124]: uwsgi socket 0 bound to UNIX address /var/run/pajbot/tibb12/web.sock fd 3
Feb 26 03:49:53 vmi1065408 pajbot-web@tibb12[135124]: Python version: 3.9.2 (default, Feb 28 2021, 17:03:44)  [GCC 10.2.1 20210110]
Feb 26 03:49:53 vmi1065408 pajbot-web@tibb12[135124]: PEP 405 virtualenv detected: venv
Feb 26 03:49:53 vmi1065408 pajbot-web@tibb12[135124]: Set PythonHome to venv
Feb 26 03:49:54 vmi1065408 pajbot-web@tibb12[135124]: Python main interpreter initialized at 0x5640e31461e0
Feb 26 03:49:54 vmi1065408 pajbot-web@tibb12[135124]: python threads support enabled
Feb 26 03:49:54 vmi1065408 pajbot-web@tibb12[135124]: your server socket listen backlog is limited to 100 connections
Feb 26 03:49:54 vmi1065408 pajbot-web@tibb12[135124]: your mercy for graceful operations on workers is 60 seconds
Feb 26 03:49:54 vmi1065408 pajbot-web@tibb12[135124]: mapped 145840 bytes (142 KB) for 1 cores
Feb 26 03:49:54 vmi1065408 pajbot-web@tibb12[135124]: *** Operational MODE: single process ***
Feb 26 03:49:55 vmi1065408 pajbot-web@tibb12[135124]: Traceback (most recent call last):
Feb 26 03:49:55 vmi1065408 pajbot-web@tibb12[135124]:   File "./app.py", line 20, in <module>
Feb 26 03:49:55 vmi1065408 pajbot-web@tibb12[135124]:     pajbot.web.init(args)
Feb 26 03:49:55 vmi1065408 pajbot-web@tibb12[135124]:   File "./pajbot/web/__init__.py", line 58, in init
Feb 26 03:49:55 vmi1065408 pajbot-web@tibb12[135124]:     import pajbot.web.routes
Feb 26 03:49:55 vmi1065408 pajbot-web@tibb12[135124]:   File "./pajbot/web/routes/__init__.py", line 1, in <module>
Feb 26 03:49:55 vmi1065408 pajbot-web@tibb12[135124]:     import pajbot.web.routes.admin
Feb 26 03:49:55 vmi1065408 pajbot-web@tibb12[135124]:   File "./pajbot/web/routes/admin/__init__.py", line 4, in <module>
Feb 26 03:49:55 vmi1065408 pajbot-web@tibb12[135124]:     import pajbot.web.routes.admin.links
Feb 26 03:49:55 vmi1065408 pajbot-web@tibb12[135124]:   File "./pajbot/web/routes/admin/links.py", line 2, in <module>
Feb 26 03:49:55 vmi1065408 pajbot-web@tibb12[135124]:     from pajbot.modules.linkchecker import BlacklistedLink, WhitelistedLink
Feb 26 03:49:55 vmi1065408 pajbot-web@tibb12[135124]:   File "./pajbot/modules/__init__.py", line 35, in <module>
Feb 26 03:49:55 vmi1065408 pajbot-web@tibb12[135124]:     from pajbot.modules.default_chat_states import DefaultChatStatesModule
Feb 26 03:49:55 vmi1065408 pajbot-web@tibb12[135124]:   File "./pajbot/modules/default_chat_states.py", line 11, in <module>
Feb 26 03:49:55 vmi1065408 pajbot-web@tibb12[135124]:     import pytimeparse
Feb 26 03:49:55 vmi1065408 pajbot-web@tibb12[135124]: ModuleNotFoundError: No module named 'pytimeparse'
Feb 26 03:49:55 vmi1065408 pajbot-web@tibb12[135124]: unable to load app 0 (mountpoint='') (callable not found or import error)
Feb 26 03:49:55 vmi1065408 pajbot-web@tibb12[135124]: *** no app loaded. GAME OVER ***
Feb 26 03:49:55 vmi1065408 pajbot-web@tibb12[135124]: VACUUM: unix socket /var/run/pajbot/tibb12/web.sock removed.
Feb 26 03:49:55 vmi1065408 systemd[1]: pajbot-web@tibb12.service: Main process exited, code=exited, status=22/n/a
Feb 26 03:49:55 vmi1065408 systemd[1]: pajbot-web@tibb12.service: Failed with result 'exit-code'.
Feb 26 03:49:55 vmi1065408 systemd[1]: pajbot-web@tibb12.service: Consumed 1.406s CPU time.
```

**Comment by ALazyMeme** [comment]
It looks like you may have missed a step when updating your bot: `Remember to bring your dependencies up to date with ./scripts/venvinstall.sh when updating to this version!`

This the command I usually run when updating all my bots: `cd /opt/pajbot && sudo -u pajbot git pull && sudo rm -rf venv && sudo -H -u pajbot ./scripts/venvinstall.sh && sudo systemctl restart pajbot{,-web}@*`

It handles the whole process including restarting the bots and their web process.

**Comment by Mr-Cheeezz** [comment]
I got an error when running the `cd /opt/pajbot && sudo -u pajbot git pull && sudo rm -rf venv && sudo -H -u pajbot ./scripts/venvinstall.sh && sudo systemctl restart pajbot{,-web}@*`
![image](https://i.mrcheeezz.com/goDxm.png)

**Comment by Mr-Cheeezz** [comment]
After reopening the terminal it worked when running the commmand

**Comment by ALazyMeme** [comment]
So do the bots work? Also I would highly suggest a few things:

- Edit history is a thing on GitHub, so if you're going to hide your IP address; delete the comment/post and re-post it
- Don't run your server as root, create a new user with sudo access and login with that. I usually disable root login on my servers.
