### ISSUE TITLE
when users whispers are off `!$timeout` does not work

### ISSUE THREAD

**Issue by Mr-Cheeezz** [pajbot/pajbot#2375]
here are the logs:
```
Mar 12 17:44:40 vmi1065408 pajbot@maycris[72126]: [2023-03-12 17:44:40,255] [DEBUG  ] Cache Miss: api:twitch:helix:user:by-id:95676405
Mar 12 17:44:40 vmi1065408 pajbot@maycris[72126]: [2023-03-12 17:44:40,256] [DEBUG  ] Successfully loaded OAuth token from storage
Mar 12 17:44:40 vmi1065408 pajbot@maycris[72126]: [2023-03-12 17:44:40,403] [DEBUG  ] Cache Miss: api:twitch:helix:user:by-id:885591395
Mar 12 17:44:40 vmi1065408 pajbot@maycris[72126]: [2023-03-12 17:44:40,492] [DEBUG  ] Cache Miss: api:twitch:helix:user:by-id:794213329
Mar 12 17:44:40 vmi1065408 pajbot@maycris[72126]: [2023-03-12 17:44:40,575] [DEBUG  ] Loaded config
Mar 12 17:44:40 vmi1065408 pajbot@maycris[72126]: [2023-03-12 17:44:40,633] [INFO   ] PostgreSQL Server notice: NOTICE:  relation "schema_version" already exists, skipping
Mar 12 17:44:40 vmi1065408 pajbot@maycris[72126]: [2023-03-12 17:44:40,635] [DEBUG  ] migrate db: current revision ID is 17
Mar 12 17:44:40 vmi1065408 pajbot@maycris[72126]: [2023-03-12 17:44:40,635] [DEBUG  ] migrate db: 0 revisions to run
Mar 12 17:44:40 vmi1065408 pajbot@maycris[72126]: [2023-03-12 17:44:40,638] [DEBUG  ] migrate redis: current revision ID is 3
Mar 12 17:44:40 vmi1065408 pajbot@maycris[72126]: [2023-03-12 17:44:40,639] [DEBUG  ] migrate redis: 0 revisions to run
Mar 12 17:44:40 vmi1065408 pajbot@maycris[72126]: [2023-03-12 17:44:40,865] [INFO   ] Set current stream chunk here to <pajbot.models.stream.StreamChunk object at 0x7f2f0c9b8100>
Mar 12 17:44:40 vmi1065408 pajbot@maycris[72126]: [2023-03-12 17:44:40,987] [INFO   ] Loaded 0 timers (0 online/0 offline)
Mar 12 17:44:41 vmi1065408 pajbot@maycris[72126]: [2023-03-12 17:44:41,653] [INFO   ] Try to load submodule with ID None
Mar 12 17:44:41 vmi1065408 pajbot@maycris[72126]: [2023-03-12 17:44:41,654] [INFO   ] Granting admin privileges to mr_cheeezz (505216805)
Mar 12 17:44:41 vmi1065408 pajbot@maycris[72126]: [2023-03-12 17:44:41,822] [DEBUG  ] Successfully loaded OAuth token from storage
Mar 12 17:44:42 vmi1065408 pajbot@maycris[72126]: [2023-03-12 17:44:42,254] [INFO   ] Successfully connected and authenticated with IRC
Mar 12 17:44:43 vmi1065408 pajbot@maycris[72126]: [2023-03-12 17:44:43,041] [INFO   ] WebSocket connection open
Mar 12 17:45:00 vmi1065408 pajbot@maycris[72126]: [2023-03-12 17:45:00,779] [DEBUG  ] Cache Miss: api:twitch:helix:stream:by-id:95676405
Mar 12 17:45:06 vmi1065408 pajbot@maycris[72126]: [2023-03-12 17:45:06,800] [DEBUG  ] UserRanksRefreshManager::_refresh function took 158.458 ms
Mar 12 17:45:08 vmi1065408 pajbot@maycris[72126]: [2023-03-12 17:45:08,803] [DEBUG  ] Replacing $(1) with
Mar 12 17:46:24 vmi1065408 pajbot@maycris[72126]: [2023-03-12 17:46:24,988] [DEBUG  ] Replacing $(1) with
Mar 12 17:46:40 vmi1065408 pajbot@maycris[72126]: [2023-03-12 17:46:40,905] [DEBUG  ] Cache Miss: api:twitch:helix:channel-information:95676405
Mar 12 17:46:48 vmi1065408 pajbot@maycris[72126]: [2023-03-12 17:46:48,908] [DEBUG  ] Replacing $(1) with
Mar 12 17:46:52 vmi1065408 pajbot@maycris[72126]: [2023-03-12 17:46:52,514] [DEBUG  ] Replacing $(1) with @ウシウィ
Mar 12 17:47:45 vmi1065408 pajbot@maycris[72126]: [2023-03-12 17:47:45,075] [DEBUG  ] Replacing $(1) with
Mar 12 17:48:40 vmi1065408 pajbot@maycris[72126]: [2023-03-12 17:48:40,829] [DEBUG  ] Cache Miss: api:twitch:helix:channel-information:95676405
Mar 12 17:49:30 vmi1065408 pajbot@maycris[72126]: [2023-03-12 17:49:30,401] [DEBUG  ] Replacing $(1) with @ウシウィ
Mar 12 17:49:40 vmi1065408 pajbot@maycris[72126]: [2023-03-12 17:49:40,770] [DEBUG  ] Cache Miss: api:twitch:helix:videos:by-id:95676405
Mar 12 17:50:20 vmi1065408 pajbot@maycris[72126]: [2023-03-12 17:50:20,886] [DEBUG  ] Cache Miss: api:twitch:helix:stream:by-id:95676405
Mar 12 17:50:23 vmi1065408 pajbot@maycris[72126]: [2023-03-12 17:50:23,803] [DEBUG  ] Rebuilding commands...
Mar 12 17:50:23 vmi1065408 pajbot@maycris[72126]: [2023-03-12 17:50:23,805] [DEBUG  ] Done rebuilding commands
Mar 12 17:50:29 vmi1065408 pajbot@maycris[72126]: [2023-03-12 17:50:29,395] [DEBUG  ] Cache Miss: api:twitch:helix:user:by-login:wussiwy
Mar 12 17:50:33 vmi1065408 pajbot@maycris[72126]: [2023-03-12 17:50:33,801] [ERROR  ] Logging an uncaught exception (ActionQueue)
Mar 12 17:50:33 vmi1065408 pajbot@maycris[72126]: Traceback (most recent call last):
Mar 12 17:50:33 vmi1065408 pajbot@maycris[72126]:   File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
Mar 12 17:50:33 vmi1065408 pajbot@maycris[72126]:     result = self.fn(*self.args, **self.kwargs)
Mar 12 17:50:33 vmi1065408 pajbot@maycris[72126]:   File "/opt/pajbot/pajbot/utils/time_method.py", line 22, in wrap
Mar 12 17:50:33 vmi1065408 pajbot@maycris[72126]:     ret = f(*args, **kwargs)
Mar 12 17:50:33 vmi1065408 pajbot@maycris[72126]: TypeError: _refresh() missing 1 required positional argument: 'action_queue'
Mar 12 17:50:40 vmi1065408 pajbot@maycris[72126]: [2023-03-12 17:50:40,725] [DEBUG  ] Cache Miss: api:twitch:helix:channel-information:95676405
```

**Comment by Mr-Cheeezz** [comment]
it does work it just does not whisper them.
