### ISSUE TITLE
Unable to determine the raffle winner, exception is raised

### ISSUE THREAD

**Issue by zneix** [pajbot/pajbot#2491]
Seems like upgrading to a newer python version might've broken things, I've performed a full system upgrade recently (Debian 11 -> 12) and that also upgraded python 3.9.x -> 3.11.2
I've been running on f4acf7a9 (commit 4058), now tried upgrading to on ff418e28 (master as of writing) (commit 4066) but this issue still persists.
```
Jul 09 21:39:25 shungite pajbot@zneix[3373541]: [2023-07-09 21:39:25,657] [ERROR  ] Logging an uncaught exception (main thread)
Jul 09 21:39:25 shungite pajbot@zneix[3373541]: Traceback (most recent call last):
Jul 09 21:39:25 shungite pajbot@zneix[3373541]:   File "/opt/pajbot/pajbot/eventloop.py", line 25, in run
Jul 09 21:39:25 shungite pajbot@zneix[3373541]:     command.target()
Jul 09 21:39:25 shungite pajbot@zneix[3373541]:   File "/opt/pajbot/pajbot/bot.py", line 633, in <lambda>
Jul 09 21:39:25 shungite pajbot@zneix[3373541]:     self.reactor.scheduler.execute_after(delay, lambda: function(*args, **kwargs))
Jul 09 21:39:25 shungite pajbot@zneix[3373541]:                                                         ^^^^^^^^^^^^^^^^^^^^^^^^^
Jul 09 21:39:25 shungite pajbot@zneix[3373541]:   File "/opt/pajbot/pajbot/modules/raffle.py", line 427, in multi_end_raffle
Jul 09 21:39:25 shungite pajbot@zneix[3373541]:     winner_ids = random.sample(self.raffle_users, num_winners)
Jul 09 21:39:25 shungite pajbot@zneix[3373541]:                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jul 09 21:39:25 shungite pajbot@zneix[3373541]:   File "/usr/lib/python3.11/random.py", line 439, in sample
Jul 09 21:39:25 shungite pajbot@zneix[3373541]:     raise TypeError("Population must be a sequence.  "
Jul 09 21:39:25 shungite pajbot@zneix[3373541]: TypeError: Population must be a sequence.  For dicts or sets, use sorted(d).
```

**Comment by Mm2PL** [comment]
It looks like Python 3.11 breaks this.

PyRight now complains about typing in `RaffleModule.multi_end_raffle`
```python
	    # pajbot/modules/raffle.py :426
        # and we can pick the winners!
        winner_ids = random.sample(self.raffle_users, num_winners)
        #                          ^^^^^^^^^^^^^^^^^
        # Argument of type "set[Unknown]" cannot be assigned to parameter "population" of type "Sequence[_T@sample]" in function "sample"
        # "set[Unknown]" is incompatible with "Sequence[_T@sample]" (Pyright reportGeneralTypeIssues)
```

https://github.com/pajbot/pajbot/blob/master/pajbot/modules/raffle.py#L427

In Python 3.10 random.sample looks like this:
```python
    def sample(self, population, k, *, counts=None):
        # [snip]
        if not isinstance(population, _Sequence):
            if isinstance(population, _Set):
                _warn('Sampling from a set deprecated\n'
                      'since Python 3.9 and will be removed in a subsequent version.',
                      DeprecationWarning, 2)
                population = tuple(population)
            else:
                raise TypeError("Population must be a sequence.  For dicts or sets, use sorted(d).")
        # [snip]
```

However Python 3.11 it just raises an exception:
```python
    def sample(self, population, k, *, counts=None):
        # [snip]
        if not isinstance(population, _Sequence):
            raise TypeError("Population must be a sequence.  "
                            "For dicts or sets, use sorted(d).")
        # [snip]
```
