### ISSUE TITLE
Having issues with bot

### ISSUE THREAD

**Issue by mr-cheeezz** [pajbot/pajbot#2545]
My pajbots have been working great for a while and then all of a sudden i was trying to make a new one for someone and the website works good but the bot itself does not I am getting this in the logs

Logs: 
```
Sep 17 01:51:13 vmi1065408 pajbot@aubreyplayz[859056]:   File "/opt/pajbot/pajbot/managers/irc.py", line 75, in start
Sep 17 01:51:13 vmi1065408 pajbot@aubreyplayz[859056]:     self._make_new_connection()
Sep 17 01:51:13 vmi1065408 pajbot@aubreyplayz[859056]:   File "/opt/pajbot/pajbot/managers/irc.py", line 95, in _make_new_connection
Sep 17 01:51:13 vmi1065408 pajbot@aubreyplayz[859056]:     self.bot.password,
Sep 17 01:51:13 vmi1065408 pajbot@aubreyplayz[859056]:   File "/opt/pajbot/pajbot/bot.py", line 321, in password
Sep 17 01:51:13 vmi1065408 pajbot@aubreyplayz[859056]:     return f"oauth:{self.bot_token_manager.token.access_token}"
Sep 17 01:51:13 vmi1065408 pajbot@aubreyplayz[859056]:   File "/opt/pajbot/pajbot/apiwrappers/authentication/token_manager.py", line 79, in token
Sep 17 01:51:13 vmi1065408 pajbot@aubreyplayz[859056]:     self.initialize()
Sep 17 01:51:13 vmi1065408 pajbot@aubreyplayz[859056]:   File "/opt/pajbot/pajbot/apiwrappers/authentication/token_manager.py", line 65, in initialize
Sep 17 01:51:13 vmi1065408 pajbot@aubreyplayz[859056]:     self._token = self.fetch_new()
Sep 17 01:51:13 vmi1065408 pajbot@aubreyplayz[859056]:   File "/opt/pajbot/pajbot/apiwrappers/authentication/token_manager.py", line 110, in fetch_new
Sep 17 01:51:13 vmi1065408 pajbot@aubreyplayz[859056]:     raise NoTokenError(f"No authentication token found for user {self.username} ({self.user_id}) in redis")
Sep 17 01:51:13 vmi1065408 pajbot@aubreyplayz[859056]: pajbot.apiwrappers.authentication.token_manager.NoTokenError: No authentication token found for user pirateavalibot (957226470) in redis
Sep 17 01:51:15 vmi1065408 pajbot@aubreyplayz[859056]: [2023-09-17 01:51:15,088] [ERROR  ] Failed to open connection, retrying in 2 seconds
Sep 17 01:51:15 vmi1065408 pajbot@aubreyplayz[859056]: Traceback (most recent call last):
Sep 17 01:51:15 vmi1065408 pajbot@aubreyplayz[859056]:   File "/opt/pajbot/pajbot/managers/irc.py", line 75, in start
Sep 17 01:51:15 vmi1065408 pajbot@aubreyplayz[859056]:     self._make_new_connection()
Sep 17 01:51:15 vmi1065408 pajbot@aubreyplayz[859056]:   File "/opt/pajbot/pajbot/managers/irc.py", line 95, in _make_new_connection
Sep 17 01:51:15 vmi1065408 pajbot@aubreyplayz[859056]:     self.bot.password,
Sep 17 01:51:15 vmi1065408 pajbot@aubreyplayz[859056]:   File "/opt/pajbot/pajbot/bot.py", line 321, in password
Sep 17 01:51:15 vmi1065408 pajbot@aubreyplayz[859056]:     return f"oauth:{self.bot_token_manager.token.access_token}"
Sep 17 01:51:15 vmi1065408 pajbot@aubreyplayz[859056]:   File "/opt/pajbot/pajbot/apiwrappers/authentication/token_manager.py", line 79, in token
Sep 17 01:51:15 vmi1065408 pajbot@aubreyplayz[859056]:     self.initialize()
Sep 17 01:51:15 vmi1065408 pajbot@aubreyplayz[859056]:   File "/opt/pajbot/pajbot/apiwrappers/authentication/token_manager.py", line 65, in initialize
Sep 17 01:51:15 vmi1065408 pajbot@aubreyplayz[859056]:     self._token = self.fetch_new()
Sep 17 01:51:15 vmi1065408 pajbot@aubreyplayz[859056]:   File "/opt/pajbot/pajbot/apiwrappers/authentication/token_manager.py", line 110, in fetch_new
Sep 17 01:51:15 vmi1065408 pajbot@aubreyplayz[859056]:     raise NoTokenError(f"No authentication token found for user {self.username} ({self.user_id}) in redis")
Sep 17 01:51:15 vmi1065408 pajbot@aubreyplayz[859056]: pajbot.apiwrappers.authentication.token_manager.NoTokenError: No authentication token found for user pirateavalibot (957226470) in redis
```

**Comment by RAnders00** [comment]
Try re-doing the authentication step: https://github.com/pajbot/pajbot/tree/master/install-docs#authenticate-the-bot

**Comment by mr-cheeezz** [comment]
Thanks that fixed it.
