### ISSUE TITLE
New werkzeug version doesn't have 'url_encode'

### ISSUE THREAD

**Issue by hotbear1110** [pajbot/pajbot#2563]
I have been trying to set up pajbot on an "new" sytem, but on the pajbot-web service I get this error:

```
Traceback (most recent call last):
  File "/opt/pajbot/app.py", line 4, in <module>
    import pajbot.web
  File "/opt/pajbot/pajbot/web/__init__.py", line 13, in <module>
    from flask_wtf.csrf import CSRFProtect
  File "/opt/pajbot/venv/lib/python3.11/site-packages/flask_wtf/__init__.py", line 4, in <module>
    from .recaptcha import Recaptcha
  File "/opt/pajbot/venv/lib/python3.11/site-packages/flask_wtf/recaptcha/__init__.py", line 1, in <module>
    from .fields import RecaptchaField
  File "/opt/pajbot/venv/lib/python3.11/site-packages/flask_wtf/recaptcha/fields.py", line 3, in <module>
    from . import widgets
  File "/opt/pajbot/venv/lib/python3.11/site-packages/flask_wtf/recaptcha/widgets.py", line 3, in <module>
    from werkzeug.urls import url_encode
ImportError: cannot import name 'url_encode' from 'werkzeug.urls' (/opt/pajbot/venv/lib/python3.11/site-packages/werkzeug/urls.py)
unable to load app 0 (mountpoint='') (callable not found or import error)
```

From what I can gather, the newer werkzeug1.x.x doesn't have 'url_encode'. I tried to set flask-wtf to be 0.14.3 instead of 1.1.1 to see if an older werkzeug version would work, but that just created another issue:

```
Traceback (most recent call last):
  File "/opt/pajbot/app.py", line 4, in <module>
    import pajbot.web
  File "/opt/pajbot/pajbot/web/__init__.py", line 13, in <module>
    from flask_wtf.csrf import CSRFProtect
  File "/opt/pajbot/venv/lib/python3.11/site-packages/flask_wtf/__init__.py", line 3, in <module>
    from .csrf import CSRFProtect, CsrfProtect
  File "/opt/pajbot/venv/lib/python3.11/site-packages/flask_wtf/csrf.py", line 10, in <module>
    from werkzeug.security import safe_str_cmp
ImportError: cannot import name 'safe_str_cmp' from 'werkzeug.security' (/opt/pajbot/venv/lib/python3.11/site-packages/werkzeug/security.py)
unable to load app 0 (mountpoint='') (callable not found or import error)
```

Setting up, I used the system version of python and ran this command:
`"sudo -H -u pajbot SKIP_PYENV=1 ./scripts/venvinstall.sh"
`

I'm on Ubuntu 23.04 and python 3.11

**Comment by pajlada** [comment]
Fixed by #2565 - feel free to re-open the issue if you're still running into issues
