### ISSUE TITLE
Flask 3.0.0 breaks the web interface

### ISSUE THREAD

**Issue by MagicHack** [pajbot/pajbot#2570]
Web server crashes on launch with flash 3, downgraded to flask 2.3.3 and it works again :)

Crash logs:
```
 [uWSGI] getting INI configuration from uwsgi_shared.ini
 *** Starting uWSGI 2.0.22 (64bit) on [Wed Oct  4 11:40:04 2023] ***
 compiled with version: 11.4.0 on 04 October 2023 15:35:54
 os: Linux-5.15.0-84-generic #93-Ubuntu SMP Tue Sep 5 17:16:10 UTC 2023
 nodename: localhost
 machine: x86_64
 clock source: unix
 pcre jit disabled
 detected number of CPU cores: 1
 current working directory: /opt/pajbot
 detected binary path: /opt/pajbot/venv/bin/uwsgi
 your processes number limit is 7403
 your memory page size is 4096 bytes
 detected max file descriptor number: 1024
 lock engine: pthread robust mutexes
 thunder lock: disabled (you can enable it with --thunder-lock)
 uwsgi socket 0 bound to UNIX address /var/run/pajbot/pepto/web.sock fd 3
 Python version: 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]
 PEP 405 virtualenv detected: venv
 Set PythonHome to venv
 Python main interpreter initialized at 0x562da44f8780
 python threads support enabled
 your server socket listen backlog is limited to 100 connections
 your mercy for graceful operations on workers is 60 seconds
 mapped 145840 bytes (142 KB) for 1 cores
 *** Operational MODE: single process ***
 Traceback (most recent call last):
   File "/opt/pajbot/./app.py", line 20, in <module>
     pajbot.web.init(args)
   File "/opt/pajbot/./pajbot/web/__init__.py", line 56, in init
     import pajbot.web.common
   File "/opt/pajbot/./pajbot/web/common/__init__.py", line 1, in <module>
    from . import assets as assets
   File "/opt/pajbot/./pajbot/web/common/assets.py", line 3, in <module>
    from flask_assets import Bundle, Environment
   File "/opt/pajbot/venv/lib/python3.10/site-packages/flask_assets.py", line 8, in <module>
     from flask import _request_ctx_stack, current_app
ImportError: cannot import name '_request_ctx_stack' from 'flask' (/opt/pajbot/venv/lib/python3.10/site-packages/flask/__init__.py)
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. GAME OVER ***
 VACUUM: unix socket /var/run/pajbot/pepto/web.sock removed.
```

**Comment by MagicHack** [comment]
> @MagicHack Can you try out this PR? #2571

Works perfectly :) thanks for the super quick fix
