### ISSUE TITLE
Website trouble.

### ISSUE THREAD

**Issue by SUSLI4EG** [pajbot/pajbot#329]
Hello. Trying to install your bot, but met trouble with uwsgi : 
```
Import error, disregard if debugging.
Traceback (most recent call last):
File "/srv/pajbot/pajbot/web/common/tasks.py", line 11, in init
from uwsgidecorators import thread, timer
File "/home/suslik/myvenv/lib/python3.5/site-packages/uwsgidecorators.py", line 10, in <module>
import uwsgi
ImportError: No module named 'uwsgi'
```
Reinstall uwsgi doesn't work. Can you help me something?

**Comment by shane-rice-bfg** [comment]
You either need to activate your virtual environment or install uwsgi into your virtual environment.

**Comment by smashedr** [comment]
You either need to activate your virtual environment or install uwsgi into your virtual environment.

**Comment by SUSLI4EG** [comment]
@smashedr Thanks for your feedback, but i actually did it on my local environment with installed uwsgi on it(

**Comment by pajlada** [comment]
@SUSLI4EG What distro are you using and how are you starting the website? Through just running `./app.py`?

**Comment by SUSLI4EG** [comment]
@pajlada distro is ubuntu 16.04. I try laucnh with\without configs - always caught this error

**Comment by smashedr** [comment]
Still not sure how you are launching it. But if you follow the setup instructions and run it as a systemd service it works fine.

```
(myvenv) 0 root@bot01 [/srv/pajbot][19:02:48]$ pip show uwsgi
Name: uWSGI
Version: 2.0.14
Summary: The uWSGI server
Home-page: UNKNOWN
Author: Unbit
Author-email: info@unbit.it
License: GPL2
Location: /srv/pajbot/myvenv/lib/python3.4/site-packages
Requires:

(myvenv) 0 root@bot01 [/srv/pajbot][19:03:06]$ cat /etc/systemd/system/uwsgi.smashedbott.service
[Unit]
Description=uwsgi for smashedbott

[Service]
PIDFile=/run/smashedbott.pid
ExecStart=/bin/bash -c 'cd /srv/pajbot; source myvenv/bin/activate; uwsgi --pidfile /run/smashedbott.pid --ini configs/smashedbott.ini -H /srv/pajbot/myvenv'
ExecReload=/bin/bash -c 'cd /srv/pajbot; source myvenv/bin/activate; uwsgi --reload /run/smashedbott.pid'

[Install]
WantedBy=multi-user.target
```

**Comment by SUSLI4EG** [comment]
@smashedr so,i can give you mine logs. Maybe i do something wrong:
`● pajbot.uwsgi.service - uwsgi for pajbot
   Loaded: loaded (/etc/systemd/system/pajbot.uwsgi.service; enabled; vendor pre
   Active: active (running) since Вс 2017-06-11 14:11:51 +05; 1h 8min ago
 Main PID: 639 (bash)
   CGroup: /system.slice/pajbot.uwsgi.service
           ├─ 639 /bin/bash -c cd /srv/pajbot; source myvenv/bin/activate; uwsgi
           ├─ 644 uwsgi --pidfile /run/pajbot.pid --ini configs/pajbot.ini -H /s
           └─1663 uwsgi --pidfile /run/pajbot.pid --ini configs/pajbot.ini -H /s

июн 11 14:13:03 pc bash[639]: [2017-06-11 14:13:03,676] [DEBUG  ] Enabling Subsc
июн 11 14:13:03 pc bash[639]: [2017-06-11 14:13:03,676] [ERROR  ] add_handler No
июн 11 14:13:03 pc bash[639]: [2017-06-11 14:13:03,677] [ERROR  ] add_handler No
июн 11 14:13:03 pc bash[639]: [2017-06-11 14:13:03,678] [DEBUG  ] Enabling Warni
июн 11 14:13:03 pc bash[639]: [uwsgi-signal] signum 0 registered (wid: 0 modifie
июн 11 14:13:04 pc bash[639]: WSGI app 0 (mountpoint='') ready in 66 seconds on 
июн 11 14:13:04 pc bash[639]: *** uWSGI is running in multiple interpreter mode 
июн 11 14:13:04 pc bash[639]: spawned uWSGI master process (pid: 644)
июн 11 14:13:04 pc bash[639]: spawned uWSGI worker 1 (pid: 1663, cores: 1)
июн 11 14:13:04 pc bash[639]: cache sweeper thread enabled

cat /etc/systemd/system/pajbot.uwsgi.service
# /etc/systemd/system/uwsgi.pajbot.service
[Unit]
Description=uwsgi for pajbot

[Service]
PIDFile=/run/pajbot.pid
ExecStart=/bin/bash -c 'cd /srv/pajbot; source myvenv/bin/activate; uwsgi --pidfile /run/pajbot.pid --ini configs/pajbot.ini -H /srv/pajbot/myvenv'
ExecReload=/bin/bash -c 'cd /srv/pajbot; source myvenv/bin/activate; uwsgi --reload /run/pajbot.pid'

[Install]
WantedBy=multi-user.target

pip show uwsgi
Name: uWSGI
Version: 2.0.15
Summary: The uWSGI server
Home-page: https://uwsgi-docs.readthedocs.io/en/latest/
Author: Unbit
Author-email: info@unbit.it
License: GPL2
Location: /home/suslik/myvenv/lib/python3.5/site-packages
Requires: 
`

**Comment by smashedr** [comment]
# Website
It looks like the website/wsgi process is running just fine based on that output. So I assume the website is running just fine?

Piecing the two posts together, my only call out is that you did not specify the full path to your venv's activate: `myvenv/bin/activate` vs `/home/suslik/myvenv/bin/activate`. I have my venv installed in `/srv/pajbot`. But if the website is running fine, I guess that is not an issue, yet.

# Bot

Re-reading the original question, I assume your issue is running the bot? How are you starting the bot? I am using PM2 per the setup instructions and simply execute `startbot.sh`:
```
0 root@bot01 [/srv/pajbot][10:14:46]$ cat startbot.sh
#!/bin/bash

export LANG="en_US.utf8"

LANG="en_US.utf8" PATH="`pwd`/myvenv/bin:$PATH" /usr/bin/pm2 start main.py --name="$1" --force --output="/var/log/pajbot/$1.log" --error="/var/log/pajbot/$1.err" --merge-logs -- --config configs/$1.ini
```

```
(myvenv) 130 root@bot01 [/srv/pajbot][19:21:39]$ ./startbot.sh smashedbott
[PM2] Starting /srv/pajbot/main.py in fork_mode (1 instance)
[PM2] Done.
┌─────────────┬────┬──────┬──────┬────────┬─────────┬────────┬─────┬──────────┬──────────┐
│ App name    │ id │ mode │ pid  │ status │ restart │ uptime │ cpu │ mem      │ watching │
├─────────────┼────┼──────┼──────┼────────┼─────────┼────────┼─────┼──────────┼──────────┤
│ smashedbott │ 0  │ fork │ 1999 │ online │ 0       │ 0s     │ 5%  │ 7.7 MB   │ disabled │
└─────────────┴────┴──────┴──────┴────────┴─────────┴────────┴─────┴──────────┴──────────┘
 Use `pm2 show <id|name>` to get more details about an app
```

Hope this is of some help. If you can provide more details on what commands you are running when you get the errors, maybe Pajlada or myself can help more.

**Comment by SUSLI4EG** [comment]
@smashedr I'm sorry for my inattention. I forgot to say, this problem only with website. If i launch bot without site - anything goes right (just typing ./main.py and bot running as well). But if i tried to launch website (with\without config), i caught error with uwsgi library (1-st post). So, you think this problem with directory of venv? Because if this true, idk why that application cann't find running uwsgi service

**Comment by smashedr** [comment]
It is my understanding, based on output provided above, that if you are running the website with systemd, there should be no reason to also manually start it with app.py. At this point, you should be able to start the bot. I am only familiar with running this setup via systemd and pm2.

@pajlada can you provide any more assistance? I am afraid I don't know enough about this bot to identify the problem, sorry.

**Comment by pajlada** [comment]
If you run the website via ./app.py then that exception is expected. That's why it says "Ignore if debugging". It's not a critical error.

If it happens while debugging (when running the website via ./app.py) the only thing missing are a few timed things to refresh thumbnails and stuff. 

If it happens in "production" (when running the website with systemd) then there's a bug. 

If I understand the thread properly, that error message is the only issue right? Does the website otherwise work as expected?
