### ISSUE TITLE
Fix two broadcast related recurring errors

### ISSUE THREAD

**Issue by DatGuy1** [pajbot/pajbot#402]
https://pastebin.com/Gtk54gjQ

**Comment by RAnders00** [comment]
Posting the stack here for readability

```
[2019-07-02 08:38:05,269] [ERROR  ] Unhandled exception in APIBase._get while reading response
Traceback (most recent call last):
  File "/usr/lib/python3.6/http/client.py", line 546, in _get_chunk_left
    chunk_left = self._read_next_chunk_size()
  File "/usr/lib/python3.6/http/client.py", line 513, in _read_next_chunk_size
    return int(line, 16)
ValueError: invalid literal for int() with base 16: b'{"_total":115,"videos":[{"title":"Looking for Team to play TI Qualifiers :) | New merchandise store !merch BUY NOW Pog - https://tinyurl.com/y5odlvj8 || [A] @AdmiralBulldog","description":null,"desc

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/http/client.py", line 563, in _readall_chunked
    chunk_left = self._get_chunk_left()
  File "/usr/lib/python3.6/http/client.py", line 548, in _get_chunk_left
    raise IncompleteRead(b'')
http.client.IncompleteRead: IncompleteRead(0 bytes read)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/admiralbullbot/pajbot/apiwrappers.py", line 37, in _get
    return response.read().decode("utf-8")
  File "/usr/lib/python3.6/http/client.py", line 456, in read
    return self._readall_chunked()
  File "/usr/lib/python3.6/http/client.py", line 570, in _readall_chunked
    raise IncompleteRead(b''.join(value))
http.client.IncompleteRead: IncompleteRead(0 bytes read)
[2019-07-02 08:38:06,254] [INFO   ] Attempting to fetch video url for broadcast34749197152
[2019-07-02 08:38:06,254] [ERROR  ] Uncaught exception in fetch_video_url
Traceback (most recent call last):
  File "/srv/admiralbullbot/pajbot/models/stream.py", line 113, in fetch_video_url_stage2
    for video in data["videos"]:
TypeError: 'NoneType' object is not subscriptable
```
