### ISSUE TITLE
Web interface can crash when link-checker module is enabled

### ISSUE THREAD

**Issue by pajlada** [pajbot/pajbot#410]
Callstack:
```
Jul 07 16:22:36 dune uwsgi[3158]: [2019-07-07 16:22:36,775] [ERROR  ] Unhandled exception
Jul 07 16:22:36 dune uwsgi[3158]: Traceback (most recent call last):
Jul 07 16:22:36 dune uwsgi[3158]:   File "/srv/pajbot/myvenv/lib/python3.5/site-packages/flask/app.py", line 1813, in full_dispatch_request
Jul 07 16:22:36 dune uwsgi[3158]:     rv = self.dispatch_request()
Jul 07 16:22:36 dune uwsgi[3158]:   File "/srv/pajbot/myvenv/lib/python3.5/site-packages/flask/app.py", line 1799, in dispatch_request
Jul 07 16:22:36 dune uwsgi[3158]:     return self.view_functions[rule.endpoint](**req.view_args)
Jul 07 16:22:36 dune uwsgi[3158]:   File "./pajbot/web/routes/base/commands.py", line 46, in command_detailed
Jul 07 16:22:36 dune uwsgi[3158]:     bot_commands_list = get_commands_list()
Jul 07 16:22:36 dune uwsgi[3158]:   File "./pajbot/web/routes/base/commands.py", line 9, in get_commands_list
Jul 07 16:22:36 dune uwsgi[3158]:     return pajbot.web.utils.get_cached_commands()
Jul 07 16:22:36 dune uwsgi[3158]:   File "./pajbot/utils.py", line 73, in wrap
Jul 07 16:22:36 dune uwsgi[3158]:     ret = f(*args)
Jul 07 16:22:36 dune uwsgi[3158]:   File "./pajbot/web/utils.py", line 106, in get_cached_commands
Jul 07 16:22:36 dune uwsgi[3158]:     socket_manager=None, module_manager=ModuleManager(None).load(), bot=None
Jul 07 16:22:36 dune uwsgi[3158]:   File "./pajbot/models/module.py", line 97, in load
Jul 07 16:22:36 dune uwsgi[3158]:     self.all_modules = [module(self.bot) for module in available_modules]
Jul 07 16:22:36 dune uwsgi[3158]:   File "./pajbot/models/module.py", line 97, in <listcomp>
Jul 07 16:22:36 dune uwsgi[3158]:     self.all_modules = [module(self.bot) for module in available_modules]
Jul 07 16:22:36 dune uwsgi[3158]:   File "./pajbot/modules/followage.py", line 60, in __init__
Jul 07 16:22:36 dune uwsgi[3158]:     self.action_queue.start()
Jul 07 16:22:36 dune uwsgi[3158]:   File "./pajbot/actions.py", line 35, in start
Jul 07 16:22:36 dune uwsgi[3158]:     t.start()
Jul 07 16:22:36 dune uwsgi[3158]:   File "/usr/lib/python3.5/threading.py", line 844, in start
Jul 07 16:22:36 dune uwsgi[3158]:     _start_new_thread(self._bootstrap, ())
Jul 07 16:22:36 dune uwsgi[3158]: RuntimeError: can't start new thread
```

The action_queue should probably be started in enable or something instead? or maybe just a lazy load when the first link is checked

**Comment by RAnders00** [comment]
I do believe this is fixed since initializing the linkchecker no longer creates an ActionQueue (since https://github.com/pajbot/pajbot/commit/94de6f2918f48094c8c079a776c0e914c3dd8499#diff-b79c3a3af53423e1d2a4a1e05e844046 )
