### ISSUE TITLE
settitle and setgame not working

### ISSUE THREAD

**Issue by alazymeme** [pajbot/pajbot#680]
Here are the logs, I'm not sure what to do FeelsDankMan

```
Nov 16 09:10:36 roboweest bash[1888]: Traceback (most recent call last):
Nov 16 09:10:36 roboweest bash[1888]:   File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
Nov 16 09:10:36 roboweest bash[1888]:     result = self.fn(*self.args, **self.kwargs)
Nov 16 09:10:36 roboweest bash[1888]:   File "/opt/pajbot/pajbot/managers/emote.py", line 66, in load_all
Nov 16 09:10:36 roboweest bash[1888]:     self.load_channel_emotes()
Nov 16 09:10:36 roboweest bash[1888]:   File "/opt/pajbot/pajbot/managers/emote.py", line 99, in load_channel_emotes
Nov 16 09:10:36 roboweest bash[1888]:     streamer
Nov 16 09:10:36 roboweest bash[1888]:   File "/opt/pajbot/pajbot/apiwrappers/twitch/legacy.py", line 67, in get_channel_emotes
Nov 16 09:10:36 roboweest bash[1888]:     force_fetch=force_fetch,
Nov 16 09:10:36 roboweest bash[1888]:   File "/opt/pajbot/pajbot/apiwrappers/response_cache.py", line 98, in cache_fetch_fn
Nov 16 09:10:36 roboweest bash[1888]:     fetch_result = fetch_fn()
Nov 16 09:10:36 roboweest bash[1888]:   File "/opt/pajbot/pajbot/apiwrappers/twitch/legacy.py", line 64, in <lambda>
Nov 16 09:10:36 roboweest bash[1888]:     fetch_fn=lambda: self.fetch_channel_emotes(channel_name),
Nov 16 09:10:36 roboweest bash[1888]:   File "/opt/pajbot/pajbot/apiwrappers/twitch/legacy.py", line 59, in fetch_channel_emotes
Nov 16 09:10:36 roboweest bash[1888]:     raise e
Nov 16 09:10:36 roboweest bash[1888]:   File "/opt/pajbot/pajbot/apiwrappers/twitch/legacy.py", line 30, in fetch_channel_emotes
Nov 16 09:10:36 roboweest bash[1888]:     resp = self.get(["channels", channel_name, "product"])
Nov 16 09:10:36 roboweest bash[1888]:   File "/opt/pajbot/pajbot/apiwrappers/twitch/base.py", line 64, in get
Nov 16 09:10:36 roboweest bash[1888]:     return self.request("GET", endpoint, params, headers, authorization).json()
Nov 16 09:10:36 roboweest bash[1888]:   File "/opt/pajbot/pajbot/apiwrappers/twitch/base.py", line 61, in request
Nov 16 09:10:36 roboweest bash[1888]:     raise e
Nov 16 09:10:36 roboweest bash[1888]:   File "/opt/pajbot/pajbot/apiwrappers/twitch/base.py", line 46, in request
Nov 16 09:10:36 roboweest bash[1888]:     return super().request(method, endpoint, params, headers, json)
Nov 16 09:10:36 roboweest bash[1888]:   File "/opt/pajbot/pajbot/apiwrappers/base.py", line 81, in request
Nov 16 09:10:36 roboweest bash[1888]:     response.raise_for_status()
Nov 16 09:10:36 roboweest bash[1888]:   File "/opt/pajbot/venv/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
Nov 16 09:10:36 roboweest bash[1888]:     raise HTTPError(http_error_msg, response=self)
Nov 16 09:10:36 roboweest bash[1888]: requests.exceptions.HTTPError: 410 Client Error: Gone for url: https://api.twitch.tv/api/channels/weest/product
Nov 16 09:10:37 roboweest bash[1888]: [2019-11-16 09:10:37,105] [ERROR  ] AttributeError caught when parsing action for action "settitle": type object 'Dispatch' has no attribute 'set_title'
Nov 16 09:10:37 roboweest bash[1888]: [2019-11-16 09:10:37,105] [ERROR  ] AttributeError caught when parsing action for action "setgame": type object 'Dispatch' has no attribute 'set_game'
Nov 16 09:10:37 roboweest bash[1888]: [2019-11-16 09:10:37,286] [DEBUG  ] Successfully loaded OAuth token from storage
```

**Comment by pajlada** [comment]
The logs are not related to your changing game or title - this is part of the occasional sub emote refresh.
