### ISSUE TITLE
Sub emote refresh doesn't work anymore, deprecated API

### ISSUE THREAD

**Issue by pajlada** [pajbot/pajbot#682]
```
[2019-11-16 11:03:16,650] [ERROR  ] Logging an uncaught exception (ActionQueue)
Traceback (most recent call last):
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/pajlada/git/pajbot/pajbot/managers/emote.py", line 66, in load_all
    self.load_channel_emotes()
  File "/home/pajlada/git/pajbot/pajbot/managers/emote.py", line 98, in load_channel_emotes
    self.tier_one_emotes, self.tier_two_emotes, self.tier_three_emotes = self.legacy_api.get_channel_emotes(
  File "/home/pajlada/git/pajbot/pajbot/apiwrappers/twitch/legacy.py", line 62, in get_channel_emotes
    return self.cache.cache_fetch_fn(
  File "/home/pajlada/git/pajbot/pajbot/apiwrappers/response_cache.py", line 98, in cache_fetch_fn
    fetch_result = fetch_fn()
  File "/home/pajlada/git/pajbot/pajbot/apiwrappers/twitch/legacy.py", line 64, in <lambda>
    fetch_fn=lambda: self.fetch_channel_emotes(channel_name),
  File "/home/pajlada/git/pajbot/pajbot/apiwrappers/twitch/legacy.py", line 59, in fetch_channel_emotes
    raise e
  File "/home/pajlada/git/pajbot/pajbot/apiwrappers/twitch/legacy.py", line 30, in fetch_channel_emotes
    resp = self.get(["channels", channel_name, "product"])
  File "/home/pajlada/git/pajbot/pajbot/apiwrappers/twitch/base.py", line 64, in get
    return self.request("GET", endpoint, params, headers, authorization).json()
  File "/home/pajlada/git/pajbot/pajbot/apiwrappers/twitch/base.py", line 61, in request
    raise e
  File "/home/pajlada/git/pajbot/pajbot/apiwrappers/twitch/base.py", line 46, in request
    return super().request(method, endpoint, params, headers, json)
  File "/home/pajlada/git/pajbot/pajbot/apiwrappers/base.py", line 81, in request
    response.raise_for_status()
  File "/home/pajlada/git/pajbot/venv/lib/python3.8/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 410 Client Error: Gone for url: https://api.twitch.tv/api/channels/pajlada/product
```

**Comment by TroyDota** [comment]
Is there any notes on this?

**Comment by RAnders00** [comment]
We need to start using the twitchemotes.com API, or we have to use a hardcoded "old" client ID that's still allowed to use this API.

**Comment by TroyDota** [comment]
The twitchemotes.com api seems better then the old client id one, is there plans for doing this? or must we implement the change?

**Comment by RAnders00** [comment]
References:
#716 
#753

**Comment by RAnders00** [comment]
New issue: #752
