### ISSUE TITLE
Deadlock errors with concurrently running background refreshes

### ISSUE THREAD

**Issue by RAnders00** [pajbot/pajbot#719]
I sometimes find these errors in my service logs:

```
Dec 13 19:47:52 h01 python3[30203]: [2019-12-13 19:47:52,119] [ERROR  ] Logging an uncaught exception (ActionQueue)
Dec 13 19:47:52 h01 python3[30203]: Traceback (most recent call last):
Dec 13 19:47:52 h01 python3[30203]:   File "/opt/pajbot/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1249, in _execute_context
Dec 13 19:47:52 h01 python3[30203]:     cursor, statement, parameters, context
Dec 13 19:47:52 h01 python3[30203]:   File "/opt/pajbot/venv/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 552, in do_execute
Dec 13 19:47:52 h01 python3[30203]:     cursor.execute(statement, parameters)
Dec 13 19:47:52 h01 python3[30203]: psycopg2.errors.DeadlockDetected: deadlock detected
Dec 13 19:47:52 h01 python3[30203]: DETAIL:  Process 30269 waits for ShareLock on transaction 20310345; blocked by process 30270.
Dec 13 19:47:52 h01 python3[30203]: Process 30270 waits for ShareLock on transaction 20310346; blocked by process 30269.
Dec 13 19:47:52 h01 python3[30203]: HINT:  See server log for query details.
Dec 13 19:47:52 h01 python3[30203]: CONTEXT:  while inserting index tuple (4620,195) in relation "user"
Dec 13 19:47:52 h01 python3[30203]: The above exception was the direct cause of the following exception:
Dec 13 19:47:52 h01 python3[30203]: Traceback (most recent call last):
Dec 13 19:47:52 h01 python3[30203]:   File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
Dec 13 19:47:52 h01 python3[30203]:     result = self.fn(*self.args, **self.kwargs)
Dec 13 19:47:52 h01 python3[30203]:   File "/opt/pajbot/pajbot/utils/time_method.py", line 18, in wrap
Dec 13 19:47:52 h01 python3[30203]:     ret = f(*args, **kwargs)
Dec 13 19:47:52 h01 python3[30203]:   File "/opt/pajbot/pajbot/modules/subscriber_fetch.py", line 112, in _update_subscribers
Dec 13 19:47:52 h01 python3[30203]:     subscriber IS TRUE"""
Dec 13 19:47:52 h01 python3[30203]:   File "/opt/pajbot/venv/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1269, in execute
Dec 13 19:47:52 h01 python3[30203]:     clause, params or {}
Dec 13 19:47:52 h01 python3[30203]:   File "/opt/pajbot/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 988, in execute
Dec 13 19:47:52 h01 python3[30203]:     return meth(self, multiparams, params)
Dec 13 19:47:52 h01 python3[30203]:   File "/opt/pajbot/venv/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
Dec 13 19:47:52 h01 python3[30203]:     return connection._execute_clauseelement(self, multiparams, params)
Dec 13 19:47:52 h01 python3[30203]:   File "/opt/pajbot/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1107, in _execute_clauseelement
Dec 13 19:47:52 h01 python3[30203]:     distilled_params,
Dec 13 19:47:52 h01 python3[30203]:   File "/opt/pajbot/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1253, in _execute_context
Dec 13 19:47:52 h01 python3[30203]:     e, statement, parameters, cursor, context
Dec 13 19:47:52 h01 python3[30203]:   File "/opt/pajbot/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1473, in _handle_dbapi_exception
Dec 13 19:47:52 h01 python3[30203]:     util.raise_from_cause(sqlalchemy_exception, exc_info)
Dec 13 19:47:52 h01 python3[30203]:   File "/opt/pajbot/venv/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
Dec 13 19:47:52 h01 python3[30203]:     reraise(type(exception), exception, tb=exc_tb, cause=cause)
Dec 13 19:47:52 h01 python3[30203]:   File "/opt/pajbot/venv/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 152, in reraise
Dec 13 19:47:52 h01 python3[30203]:     raise value.with_traceback(tb)
Dec 13 19:47:52 h01 python3[30203]:   File "/opt/pajbot/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1249, in _execute_context
Dec 13 19:47:52 h01 python3[30203]:     cursor, statement, parameters, context
Dec 13 19:47:52 h01 python3[30203]:   File "/opt/pajbot/venv/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 552, in do_execute
Dec 13 19:47:52 h01 python3[30203]:     cursor.execute(statement, parameters)
Dec 13 19:47:52 h01 python3[30203]: sqlalchemy.exc.OperationalError: (psycopg2.errors.DeadlockDetected) deadlock detected
Dec 13 19:47:52 h01 python3[30203]: DETAIL:  Process 30269 waits for ShareLock on transaction 20310345; blocked by process 30270.
Dec 13 19:47:52 h01 python3[30203]: Process 30270 waits for ShareLock on transaction 20310346; blocked by process 30269.
Dec 13 19:47:52 h01 python3[30203]: HINT:  See server log for query details.
Dec 13 19:47:52 h01 python3[30203]: CONTEXT:  while inserting index tuple (4620,195) in relation "user"
Dec 13 19:47:52 h01 python3[30203]: [SQL:
Dec 13 19:47:52 h01 python3[30203]: WITH updated_users AS (
Dec 13 19:47:52 h01 python3[30203]:     INSERT INTO "user"(id, login, name, subscriber)
Dec 13 19:47:52 h01 python3[30203]:         SELECT id, login, name, TRUE FROM subscribers
Dec 13 19:47:52 h01 python3[30203]:     ON CONFLICT (id) DO UPDATE SET
Dec 13 19:47:52 h01 python3[30203]:         login = excluded.login,
Dec 13 19:47:52 h01 python3[30203]:         name = excluded.name,
Dec 13 19:47:52 h01 python3[30203]:         subscriber = TRUE
Dec 13 19:47:52 h01 python3[30203]:     RETURNING id
Dec 13 19:47:52 h01 python3[30203]: )
Dec 13 19:47:52 h01 python3[30203]: UPDATE "user"
Dec 13 19:47:52 h01 python3[30203]: SET
Dec 13 19:47:52 h01 python3[30203]:     subscriber = FALSE
Dec 13 19:47:52 h01 python3[30203]: WHERE
Dec 13 19:47:52 h01 python3[30203]:     id NOT IN (SELECT * FROM updated_users) AND
Dec 13 19:47:52 h01 python3[30203]:     subscriber IS TRUE]
Dec 13 19:47:52 h01 python3[30203]: (Background on this error at: http://sqlalche.me/e/e3q8)
```

PostgreSQL server log:

```
2019-12-13 19:47:52.113 CET [30269] pajbot@pajbot ERROR:  deadlock detected
2019-12-13 19:47:52.113 CET [30269] pajbot@pajbot DETAIL:  Process 30269 waits for ShareLock on transaction 20310345; blocked by process 30270.
        Process 30270 waits for ShareLock on transaction 20310346; blocked by process 30269.
        Process 30269:
        WITH updated_users AS (
            INSERT INTO "user"(id, login, name, subscriber)
                SELECT id, login, name, TRUE FROM subscribers
            ON CONFLICT (id) DO UPDATE SET
                login = excluded.login,
                name = excluded.name,
                subscriber = TRUE
            RETURNING id
        )
        UPDATE "user"
        SET
            subscriber = FALSE
        WHERE
            id NOT IN (SELECT * FROM updated_users) AND
            subscriber IS TRUE
        Process 30270:
        INSERT INTO "user"(id, login, name, points, time_in_chat_online, time_in_chat_offline, last_seen)
            VALUES ('69693744', 'kawazoo', 'Kawazoo', 5, '0 days 600.000000 seconds'::interval, '0 days 0.000000 seconds'::interval, now())
        ON CONFLICT (id) DO UPDATE SET
            points = "user".points + CASE WHEN "user".subscriber THEN 10 ELSE 5 END,
            time_in_chat_online = "user".time_in_chat_online + '0 days 600.000000 seconds'::interval,
            time_in_chat_offline = "user".time_in_chat_offline + '0 days 0.000000 seconds'::interval,
            last_seen = now()

2019-12-13 19:47:52.113 CET [30269] pajbot@pajbot HINT:  See server log for query details.
2019-12-13 19:47:52.113 CET [30269] pajbot@pajbot CONTEXT:  while inserting index tuple (4620,195) in relation "user"
2019-12-13 19:47:52.113 CET [30269] pajbot@pajbot STATEMENT:
        WITH updated_users AS (
            INSERT INTO "user"(id, login, name, subscriber)
                SELECT id, login, name, TRUE FROM subscribers
            ON CONFLICT (id) DO UPDATE SET
                login = excluded.login,
                name = excluded.name,
                subscriber = TRUE
            RETURNING id
        )
        UPDATE "user"
        SET
            subscriber = FALSE
        WHERE
            id NOT IN (SELECT * FROM updated_users) AND
            subscriber IS TRUE
```

**Comment by RAnders00** [comment]
It might be possible to solve this problem if we always process users in the exact same order, by sorting by their ID for example.

**Comment by TroyDota** [comment]
I don't get this error message?

**Comment by RAnders00** [comment]
It happens randomly only for me and only on large bots

**Comment by TroyDota** [comment]
I get this error message

**Comment by TroyDota** [comment]
What are the effects of the deadlock running?

**Comment by RAnders00** [comment]
The effect of this error is that one cycle of the deadlocked refresh will abort without any changes (the database transactions are rolled back and the scheduled task is aborted because of the exception)

The effect is arguably very minor.

**Comment by RAnders00** [comment]
given that this has become rare and I've not seen this for a very long time I'm closing the issue
