### ISSUE TITLE
Emote manager missing API

### ISSUE THREAD

**Issue by DatGuy1** [pajbot/pajbot#759]
```
Traceback (most recent call last):
  File "python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "pajbot/managers/emote.py", line 61, in update_all
    self.update_global_emotes()
  File "pajbot/managers/emote.py", line 51, in update_global_emotes
    self.global_emotes = self.api.get_global_emotes(force_fetch=True)
AttributeError: 'TwitchEmotesAPI' object has no attribute 'get_global_emotes'
```

**Comment by TroyDota** [comment]
The legacy api was used for this.
