### ISSUE TITLE
flask-oauthlib has been deprecated

### ISSUE THREAD

**Issue by Leppunen** [pajbot/pajbot#816]
This causes issues with the recent release of werkzeug 1.0.0 that breaks this library.

[authlib](https://github.com/lepture/authlib) is what the developer is recommending everyone to migrate to.

**Comment by RAnders00** [comment]
Where do we use werkzeug in the project (and in a way that pulls in the new 1.0.0 version)? Don't we pin all the imported versions via requirements.txt?

**Comment by RAnders00** [comment]
```
Traceback (most recent call last):
  File "/home/ruben/git/pajbot/app.py", line 20, in <module>
    pajbot.web.init(args)
  File "/home/ruben/git/pajbot/pajbot/web/__init__.py", line 35, in init
    import pajbot.web.routes
  File "/home/ruben/git/pajbot/pajbot/web/routes/__init__.py", line 3, in <module>
    import pajbot.web.routes.base
  File "/home/ruben/git/pajbot/pajbot/web/routes/base/__init__.py", line 5, in <module>
    import pajbot.web.routes.base.login
  File "/home/ruben/git/pajbot/pajbot/web/routes/base/login.py", line 9, in <module>
    from flask_oauthlib.client import OAuth
  File "/home/ruben/git/pajbot/venv/lib/python3.7/site-packages/flask_oauthlib/client.py", line 18, in <module>
    from werkzeug import url_quote, url_decode, url_encode
ImportError: cannot import name 'url_quote' from 'werkzeug' (/home/ruben/git/pajbot/venv/lib/python3.7/site-packages/werkzeug/__init__.py)
```

**Comment by pajlada** [comment]
Not fully fixed, just bandaged. Reopening
