### ISSUE TITLE
subemotes no longer works

### ISSUE THREAD

**Issue by alazymeme** [pajbot/pajbot#858]
Maybe no longer working after the latest oauth changes to kraken

**Comment by RAnders00** [comment]
They work for me. Sub emotes are fetched from twitchemotes.com.
Could you care to elaborate in what way sub emotes are not working?

**Comment by alazymeme** [comment]
@RAnders00 Are you sure they aren't already cached or something?
![image](https://user-images.githubusercontent.com/12804673/81467491-45711580-921c-11ea-9dd3-a9f933c9e26f.png)

```
May 09 09:22:04 MainServer pajbot@alazymeme[22555]: Traceback (most recent call last):
May 09 09:22:04 MainServer pajbot@alazymeme[22555]:   File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
May 09 09:22:04 MainServer pajbot@alazymeme[22555]:     result = self.fn(*self.args, **self.kwargs)
May 09 09:22:04 MainServer pajbot@alazymeme[22555]:   File "/opt/pajbot/pajbot/managers/emote.py", line 61, in update_all
May 09 09:22:04 MainServer pajbot@alazymeme[22555]:     self.update_global_emotes()
May 09 09:22:04 MainServer pajbot@alazymeme[22555]:   File "/opt/pajbot/pajbot/managers/emote.py", line 101, in update_global_emotes
May 09 09:22:04 MainServer pajbot@alazymeme[22555]:     self.global_emotes = self.twitch_v5_api.get_global_emotes(force_fetch=True)
May 09 09:22:04 MainServer pajbot@alazymeme[22555]:   File "/opt/pajbot/pajbot/apiwrappers/twitch/kraken_v5.py", line 82, in get_global_emotes
May 09 09:22:04 MainServer pajbot@alazymeme[22555]:     force_fetch=force_fetch,
May 09 09:22:04 MainServer pajbot@alazymeme[22555]:   File "/opt/pajbot/pajbot/apiwrappers/response_cache.py", line 98, in cache_fetch_fn
May 09 09:22:04 MainServer pajbot@alazymeme[22555]:     fetch_result = fetch_fn()
May 09 09:22:04 MainServer pajbot@alazymeme[22555]:   File "/opt/pajbot/pajbot/apiwrappers/twitch/kraken_v5.py", line 79, in <lambda>
May 09 09:22:04 MainServer pajbot@alazymeme[22555]:     fetch_fn=lambda: self.fetch_global_emotes(),
May 09 09:22:04 MainServer pajbot@alazymeme[22555]:   File "/opt/pajbot/pajbot/apiwrappers/twitch/kraken_v5.py", line 73, in fetch_global_emotes
May 09 09:22:04 MainServer pajbot@alazymeme[22555]:     resp = self.get("/chat/emoticon_images", params={"emotesets": "0"})
May 09 09:22:04 MainServer pajbot@alazymeme[22555]:   File "/opt/pajbot/pajbot/apiwrappers/twitch/base.py", line 67, in get
May 09 09:22:04 MainServer pajbot@alazymeme[22555]:     return self.request("GET", endpoint, params, headers, authorization).json()
May 09 09:22:04 MainServer pajbot@alazymeme[22555]:   File "/opt/pajbot/pajbot/apiwrappers/twitch/base.py", line 64, in request
May 09 09:22:04 MainServer pajbot@alazymeme[22555]:     raise e
May 09 09:22:04 MainServer pajbot@alazymeme[22555]:   File "/opt/pajbot/pajbot/apiwrappers/twitch/base.py", line 49, in request
May 09 09:22:04 MainServer pajbot@alazymeme[22555]:     return super().request(method, endpoint, params, headers, json)
May 09 09:22:04 MainServer pajbot@alazymeme[22555]:   File "/opt/pajbot/pajbot/apiwrappers/base.py", line 81, in request
May 09 09:22:04 MainServer pajbot@alazymeme[22555]:     response.raise_for_status()
May 09 09:22:04 MainServer pajbot@alazymeme[22555]:   File "/opt/pajbot/venv/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
May 09 09:22:04 MainServer pajbot@alazymeme[22555]:     raise HTTPError(http_error_msg, response=self)
May 09 09:22:04 MainServer pajbot@alazymeme[22555]: requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://api.twitch.tv/kraken/chat/emoticon_images?emotesets=0
```

**Comment by RAnders00** [comment]
`requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://api.twitch.tv/kraken/chat/emoticon_images?emotesets=0`

I think if you read that, that will answer your questions. The error you are reading from your logs was a temporarily failure on Twitch servers, and it was for fetching the global emotes.

**Comment by alazymeme** [comment]
hmm
Well this error only happens when I run the `!subemotes reload` command.

**Comment by RAnders00** [comment]
I think Twitch API is just currently broken on that endpoint, not much we can do about that.

However, we can make it so it tries to refresh sub emotes regardless of whether global emotes refresh successfully.

```
> GET /kraken/chat/emoticon_images?emotesets=0&client_id=472wm7d2oxkundpqsy1abmjjxqnuiq&api_version=5 HTTP/1.1

< HTTP/1.1 500 Internal Server Error
< {
<   "error": "Internal Server Error",
<   "status": 500,
<   "message": ""
< }

**Comment by RAnders00** [comment]
https://github.com/twitchdev/issues/issues/107 - linked issue

**Comment by BarryCarlyon** [comment]
https://twitch.uservoice.com/forums/310213-developers/suggestions/39547780-emotes-by-channelid

Might wanna upvote this one so emotes can be fetched better/by channel ID

**Comment by RAnders00** [comment]
Endpoint now works properly again
