### ISSUE TITLE
Using a numbered variable within the lasttweet variable returns an error

### ISSUE THREAD

**Issue by alazymeme** [pajbot/pajbot#918]
![image](https://user-images.githubusercontent.com/12804673/84765085-0e0f3900-b012-11ea-9d05-d31200a08f01.png)
![image](https://user-images.githubusercontent.com/12804673/84765093-136c8380-b012-11ea-854f-a3b55e5d830e.png)
```
Jun 16 12:45:07 MainServer pajbot@alazymeme[28436]: Traceback (most recent call last):
Jun 16 12:45:07 MainServer pajbot@alazymeme[28436]:   File "/opt/pajbot/pajbot/managers/twitter.py", line 103, in get_last_tweet
Jun 16 12:45:07 MainServer pajbot@alazymeme[28436]:     public_tweets = self.twitter_client.user_timeline(username)
Jun 16 12:45:07 MainServer pajbot@alazymeme[28436]:   File "/opt/pajbot/venv/lib/python3.6/site-packages/tweepy/binder.py", line 250, in _call
Jun 16 12:45:07 MainServer pajbot@alazymeme[28436]:     return method.execute()
Jun 16 12:45:07 MainServer pajbot@alazymeme[28436]:   File "/opt/pajbot/venv/lib/python3.6/site-packages/tweepy/binder.py", line 233, in execute
Jun 16 12:45:07 MainServer pajbot@alazymeme[28436]:     raise TweepError(error_msg, resp, api_code=api_error_code)
Jun 16 12:45:07 MainServer pajbot@alazymeme[28436]: tweepy.error.TweepError: [{'code': 34, 'message': 'Sorry, that page does not exist.'}]
Jun 16 12:45:07 MainServer pajbot@alazymeme[28436]: [2020-06-16 12:45:07,551] [DEBUG  ] Replacing $(1) with alazymeme

**Comment by TroyDota** [comment]
Is it order of operations?

**Comment by badoge** [comment]
using a semicolon instead of a colon works ¯\_(ツ)_/¯

![image](https://user-images.githubusercontent.com/18620902/104847509-d9da5e80-58f9-11eb-9781-5364b86faf49.png)

**Comment by RAnders00** [comment]
@alazymeme is this good enough for you? I didnt know that was possible either 😄

**Comment by alazymeme** [comment]
> @alazymeme is this good enough for you? I didnt know that was possible either 😄

Will close with a pr - adding this to the variables doc. If anyone else wishes to do it, they can. Will get to it on the weekend otherwise
