### ISSUE TITLE
no response when trying to change title/game

### ISSUE THREAD

**Issue by alazymeme** [pajbot/pajbot#923]
![image](https://user-images.githubusercontent.com/12804673/85252110-5dd08300-b49e-11ea-9bcb-2a8cd98fae91.png)

```Jun 22 07:36:37 MainServer pajbot@hyphin[11463]: requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://id.twitch.tv/oauth2/token?client_id=xd&client_secret=xd&grant_type=refresh_token&refresh_token=xd
Jun 22 07:37:09 MainServer pajbot@hyphin[11463]: [2020-06-22 07:37:09,470] [DEBUG  ] Refreshing OAuth token
Jun 22 07:37:09 MainServer pajbot@hyphin[11463]: [2020-06-22 07:37:09,790] [DEBUG  ] Returning 0 tokens to ALazyMeme
Jun 22 07:37:09 MainServer pajbot@hyphin[11463]: [2020-06-22 07:37:09,791] [DEBUG  ] Returning 0 points to ALazyMeme
Jun 22 07:37:09 MainServer pajbot@hyphin[11463]: [2020-06-22 07:37:09,791] [ERROR  ] Logging an uncaught exception (IRC event handler)
Jun 22 07:37:09 MainServer pajbot@hyphin[11463]: Traceback (most recent call last):
Jun 22 07:37:09 MainServer pajbot@hyphin[11463]:   File "/opt/pajbot/pajbot/managers/irc.py", line 142, in _dispatcher
Jun 22 07:37:09 MainServer pajbot@hyphin[11463]:     method(conn, event)
Jun 22 07:37:09 MainServer pajbot@hyphin[11463]:   File "/opt/pajbot/pajbot/bot.py", line 793, in on_pubmsg
Jun 22 07:37:09 MainServer pajbot@hyphin[11463]:     self.parse_message(event.arguments[0], source, event, tags=tags)
Jun 22 07:37:09 MainServer pajbot@hyphin[11463]:   File "/opt/pajbot/pajbot/bot.py", line 714, in parse_message
Jun 22 07:37:09 MainServer pajbot@hyphin[11463]:     command.run(self, source, remaining_message, event=event, args=extra_args, whisper=whisper)
Jun 22 07:37:09 MainServer pajbot@hyphin[11463]:   File "/opt/pajbot/pajbot/models/command.py", line 417, in run
Jun 22 07:37:09 MainServer pajbot@hyphin[11463]:     self.run_action(bot, source, message, event, args)
Jun 22 07:37:09 MainServer pajbot@hyphin[11463]:   File "/opt/pajbot/pajbot/models/command.py", line 424, in run_action
Jun 22 07:37:09 MainServer pajbot@hyphin[11463]:     ret = self.action.run(bot, source, message, event, args)
Jun 22 07:37:09 MainServer pajbot@hyphin[11463]:   File "/opt/pajbot/pajbot/models/action.py", line 247, in run
Jun 22 07:37:09 MainServer pajbot@hyphin[11463]:     return self.cb(bot=bot, source=source, message=message, event=event, args=args)
Jun 22 07:37:09 MainServer pajbot@hyphin[11463]:   File "/opt/pajbot/pajbot/modules/basic/stream_update.py", line 76, in update_game
Jun 22 07:37:09 MainServer pajbot@hyphin[11463]:     self.generic_update(bot, source, message, "game", self.bot.twitch_v5_api.set_game)
Jun 22 07:37:09 MainServer pajbot@hyphin[11463]:   File "/opt/pajbot/pajbot/modules/basic/stream_update.py", line 57, in generic_update
Jun 22 07:37:09 MainServer pajbot@hyphin[11463]:     if "channel_editor" in bot.streamer_access_token_manager.token.scope:
Jun 22 07:37:09 MainServer pajbot@hyphin[11463]:   File "/opt/pajbot/pajbot/apiwrappers/authentication/token_manager.py", line 78, in token
Jun 22 07:37:09 MainServer pajbot@hyphin[11463]:     self.refresh()
Jun 22 07:37:09 MainServer pajbot@hyphin[11463]:   File "/opt/pajbot/pajbot/apiwrappers/authentication/token_manager.py", line 49, in refresh
Jun 22 07:37:09 MainServer pajbot@hyphin[11463]:     new_token = self._token.refresh(self.api)
Jun 22 07:37:09 MainServer pajbot@hyphin[11463]:   File "/opt/pajbot/pajbot/apiwrappers/authentication/access_token.py", line 129, in refresh
Jun 22 07:37:09 MainServer pajbot@hyphin[11463]:     return api.refresh_user_access_token(self.refresh_token)
Jun 22 07:37:09 MainServer pajbot@hyphin[11463]:   File "/opt/pajbot/pajbot/apiwrappers/twitch/id.py", line 62, in refresh_user_access_token
Jun 22 07:37:09 MainServer pajbot@hyphin[11463]:     "refresh_token": refresh_token,
Jun 22 07:37:09 MainServer pajbot@hyphin[11463]:   File "/opt/pajbot/pajbot/apiwrappers/base.py", line 94, in post
Jun 22 07:37:09 MainServer pajbot@hyphin[11463]:     return self.request("POST", endpoint, params, headers, json, **request_options).json()
Jun 22 07:37:09 MainServer pajbot@hyphin[11463]:   File "/opt/pajbot/pajbot/apiwrappers/base.py", line 81, in request
Jun 22 07:37:09 MainServer pajbot@hyphin[11463]:     response.raise_for_status()
Jun 22 07:37:09 MainServer pajbot@hyphin[11463]:   File "/opt/pajbot/venv/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
Jun 22 07:37:09 MainServer pajbot@hyphin[11463]:     raise HTTPError(http_error_msg, response=self)
Jun 22 07:37:09 MainServer pajbot@hyphin[11463]: requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://id.twitch.tv/oauth2/token?client_id=xd&client_secret=xd&grant_type=refresh_token&refresh_token=xd

**Comment by TroyDota** [comment]
Api seemed to be down? Is it still bugged?

**Comment by RAnders00** [comment]
I don't know what could cause a 400 Bad Request on that OAuth endpoint. Maybe an invalid token raises 400?

**Comment by alazymeme** [comment]
> I don't know what could cause a 400 Bad Request on that OAuth endpoint. Maybe an invalid token raises 400?

I moved all the applications to my main bot account. So I changed the client ID and token for the bot. The main issue I had was that there was no bot output.

**Comment by TroyDota** [comment]
Oh you want to catch the error?

**Comment by alazymeme** [comment]
> Oh you want to catch the error?

I mean the streamer and mods had no idea what was happening. It would be helpful if there were some form of chat error output.

**Comment by MagicHack** [comment]
I have this exact same thing happening right now. The only thing that changed between settitle working and not is the streamer got affiliate. I asked him to to do the streamer_login again and it still doesn't work, so I'm not sure how to fix it. Do I need to make a new dev app?

**Comment by alazymeme** [comment]
> I have this exact same thing happening right now. The only thing that changed between settitle working and not is the streamer got affiliate. I asked him to to do the streamer_login again and it still doesn't work, so I'm not sure how to fix it. Do I need to make a new dev app?

Get the streamer to remove the connections on the twitch connections page, then relogin to the streamer_login endpoint and restart the bot.
